# Standing Light Punch
[[move]]
name = "Standing Light Punch"
name_ja = "立ち弱パン"
alternativeNames = [ "Jab" ]
alternativeNames_ja = [ "小パン", "コパン" ]
slug = "cammy-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5lp"
notes = [ ]
notes_ja = [ ]

# Standing Medium Punch
[[move]]
name = "Standing Medium Punch"
name_ja = "立ち中パン"
alternativeNames = [ "Strong" ]
alternativeNames_ja = [ "中パン" ]
slug = "cammy-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5mp"

# Standing Heavy Punch
[[move]]
name = "Standing Heavy Punch"
name_ja = "立ち強パン"
alternativeNames = [ "Fierce" ]
alternativeNames_ja = [ "大パン" ]
slug = "cammy-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5hp"

# Standing Light Kick
[[move]]
name = "Standing Light Kick"
name_ja = "立ち弱キック"
alternativeNames = [ "Short" ]
alternativeNames_ja = [ "小足", "コアシ" ]
slug = "cammy-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5lk"

# Standing Medium Kick
[[move]]
name = "Standing Medium Kick"
name_ja = "立ち中キック"
alternativeNames = [ "Forward" ]
alternativeNames_ja = [ "中足", "中アシ" ]
slug = "cammy-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5mk"

# Standing Heavy Kick
[[move]]
name = "Standing Heavy Kick"
name_ja = "立ち強キック"
alternativeNames = [ "Roundhouse" ]
alternativeNames_ja = [ "大足", "大アシ" ]
slug = "cammy-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5hk"

# Crouching Light Punch
[[move]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱パン"
alternativeNames = [ "Crouching jab" ]
alternativeNames_ja = [ "しゃがみ小パン", "しゃがみコパン" ]
slug = "cammy-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2lp"

# Crouching Medium Punch
[[move]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中パン"
alternativeNames = [ "Crouching jab" ]
alternativeNames_ja = [ "しゃがみ中パン" ]
slug = "cammy-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2mp"

# Crouching Heavy Punch
[[move]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強パン"
alternativeNames = [ "Crouching strong" ]
alternativeNames_ja = [ "しゃがみ大パン" ]
slug = "cammy-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2hp"

# Crouching Light Kick
[[move]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱キック"
alternativeNames = [ "Crouching short" ]
alternativeNames_ja = [ "しゃがみ小足", "しゃがみコアシ" ]
slug = "cammy-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2lk"

# Crouch Medium Kick
[[move]]
name = "Crouch Medium Kick"
name_ja = "しゃがみ中キック"
alternativeNames = [ "Crouching forward" ]
alternativeNames_ja = [ "しゃがみ中足", "しゃがみ中アシ" ]
slug = "cammy-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2mk"

# Crouching Heavy Kick
[[move]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強キック"
alternativeNames = [ "Crouching forward" ]
alternativeNames_ja = [ "しゃがみ大足", "しゃがみ大アシ" ]
slug = "cammy-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2hk"

# Jumping Light Punch
[[move]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱パン"
alternativeNames = [ "Crouching forward" ]
alternativeNames_ja = [ "ジャンプ小パン", "ジャンプコパン" ]
slug = "cammy-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jlp"

# Jumping Medium Punch
[[move]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中パン"
alternativeNames = [ "Jumping strong" ]
alternativeNames_ja = [ "ジャンプ中パン" ]
slug = "cammy-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jmp"

# Jumping Heavy Punch
[[move]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強パン"
alternativeNames = [ "Jumping roundhouse" ]
alternativeNames_ja = [ "ジャンプ大パン" ]
slug = "cammy-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jhp"

# Jumping Light Kick
[[move]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱キック"
alternativeNames = [ "Jumping short" ]
alternativeNames_ja = [ "ジャンプ小足", "ジャンプコアシ" ]
slug = "cammy-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jlk"

# Jumping Medium Kick
[[move]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中キック"
alternativeNames = [ "Jumping forward" ]
alternativeNames_ja = [ "ジャンプ中足", "ジャンプ中アシ" ]
slug = "cammy-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jmk"

# Jumping Heavy Kick
[[move]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強キック"
alternativeNames = [ "Jumping roundhouse" ]
alternativeNames_ja = [ "ジャンプ大足", "ジャンプ大アシ" ]
slug = "cammy-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 17
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jhk"
