# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱パン"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "dhalsim-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中パン"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "dhalsim-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強パン"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "dhalsim-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱キック"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "dhalsim-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中キック"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "dhalsim-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強キック"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "dhalsim-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "dhalsim-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ中パン"]
slug = "dhalsim-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強パン"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "dhalsim-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱キック"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "dhalsim-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "dhalsim-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "dhalsim-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱パン"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "dhalsim-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中パン"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン"]
slug = "dhalsim-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強パン"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "dhalsim-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hp"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱キック"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "dhalsim-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中キック"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "dhalsim-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強キック"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "dhalsim-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 9
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hk"

# Yoga Uppercut
[[moves]]
name = "Yoga Uppercut"
name_ja = "ヨガアッパー"
slug = "yoga-uppercut"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4mp"

# Yoga Lance
[[moves]]
name = "Yoga Lance"
name_ja = "ヨガランス"
slug = "yoga-lance"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4hp"

# Nirvana Punch
[[moves]]
name = "Nirvana Punch"
name_ja = "涅槃パンチ"
slug = "nirvana-punch"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "1hp"

# Agile Kick
[[moves]]
name = "Agile Kick"
name_ja = "アジャイルキック"
slug = "agile-kick"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "low"
input = "1lk"

# Divine Kick
[[moves]]
name = "Divine Kick"
name_ja = "合掌キック"
slug = "divine-kick"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4mk"

# Thrust Kick
[[moves]]
name = "Thrust Kick"
name_ja = "スラストキック"
slug = "thrust-kick"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "low"
input = "1mk"

# Yoga Mountain
[[moves]]
name = "Yoga Mountain"
name_ja = "ヨガマウンテン"
slug = "yoga-mountain"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4hk"

# Karma Kick
[[moves]]
name = "Karma Kick"
name_ja = "因果キック"
slug = "karma-kick"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "1hk"

# Yoga Mummy
[[moves]]
name = "Yoga Mummy"
name_ja = "ヨガマミー"
slug = "yoga-mummy"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "jumpIn"
input = "j>2lp"

# Drill Kick
[[moves]]
name = "Drill Kick"
name_ja = "ドリルキック"
slug = "drill-kick"
characterId = 9
type = "commandNormal"
hitCount = 1
blockType = "jumpIn"
input = "j>2*k"

# Yoga Fire
[[moves]]
name = "Yoga Fire"
name_ja = "ヨガファイア"
slug = "yoga-fire"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "236*p"
properties = ["chargeable"]

# Yoga Fire (OD)
[[moves]]
name = "Yoga Fire (OD)"
name_ja = "ヨガファイア（OD）"
slug = "yoga-fire-od"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "236(pp)"
properties = ["chargeable"]

# Yoga Arch
[[moves]]
name = "Yoga Arch"
name_ja = "ヨガアーチ"
slug = "yoga-arch"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "236*p"

# Yoga Arch (OD)
[[moves]]
name = "Yoga Arch (OD)"
name_ja = "ヨガアーチ（OD）"
slug = "yoga-arch-od"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "236(pp)"

# Yoga Flame (Light)
[[moves]]
name = "Yoga Flame (Light)"
name_ja = "ヨガフレイム（弱）"
slug = "yoga-flame-light"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214lp"

# Yoga Flame (Medium)
[[moves]]
name = "Yoga Flame (Medium)"
name_ja = "ヨガフレイム（中）"
slug = "yoga-flame-medium"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214mp"

# Yoga Flame (Heavy)
[[moves]]
name = "Yoga Flame (Heavy)"
name_ja = "ヨガフレイム（強）"
slug = "yoga-flame-heavy"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214hp"

# Yoga Flame (OD)
[[moves]]
name = "Yoga Flame (OD)"
name_ja = "ヨガフレイム（OD）"
slug = "yoga-flame-od"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214(pp)"

# Yoga Blast (Light)
[[moves]]
name = "Yoga Blast (Light)"
name_ja = "ヨガブラスト（弱）"
slug = "yoga-blast-light"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214lk"

# Yoga Blast (Medium)
[[moves]]
name = "Yoga Blast (Medium)"
name_ja = "ヨガブラスト（中）"
slug = "yoga-blast-medium"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214mk"

# Yoga Blast (Heavy)
[[moves]]
name = "Yoga Blast (Heavy)"
name_ja = "ヨガブラスト（強）"
slug = "yoga-blast-heavy"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214hk"

# Yoga Blast (OD)
[[moves]]
name = "Yoga Blast (OD)"
name_ja = "ヨガブラスト（OD）"
slug = "yoga-blast-od"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "63214(pp)"

# Yoga Comet
[[moves]]
name = "Yoga Comet"
name_ja = "ヨガコメット"
slug = "yoga-comet"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "j>63214*p"

# Yoga Comet (OD)
[[moves]]
name = "Yoga Comet (OD)"
name_ja = "ヨガコメット（OD）"
slug = "yoga-comet-od"
characterId = 9
type = "special"
hitCount = 1
blockType = "high"
input = "j>63214(pp)"

# Yoga Float
[[moves]]
name = "Yoga Float"
name_ja = "ヨガフロート"
slug = "yoga-float"
characterId = 9
type = "action"
input = "2(kk)|3(kk)"

# Aerial Yoga Float
[[moves]]
name = "Aerial Yoga Float"
name_ja = "空中ヨガフロート"
slug = "aerial-yoga-float"
characterId = 9
type = "action"
input = "j>2(kk)"

# Yoga Teleport
[[moves]]
name = "Yoga Teleport"
name_ja = "ヨガテレポート"
slug = "yoga-teleport"
characterId = 9
type = "action"
input = "4(ppp)(kkk)|6(ppp)(kkk)"

# Aerial Yoga Teleport
[[moves]]
name = "Aerial Yoga Teleport"
name_ja = "空中ヨガテレポート"
slug = "aerial-yoga-teleport"
characterId = 9
type = "action"
input = "j>>4(ppp)(kkk)|6(ppp)(kkk)"

# Yoga Inferno
[[moves]]
name = "Yoga Inferno"
name_ja = "ヨガインフェルノ"
slug = "yoga-inferno"
characterId = 9
type = "super1"
hitCount = 1
blockType = "high"
input = "236236*p"

# Yoga Sunburst
[[moves]]
name = "Yoga Sunburst"
name_ja = "ヨガサンバースト"
slug = "yoga-sunburst"
characterId = 9
type = "super2"
hitCount = 1
blockType = "high"
input = "214214*k"

# Yoga Sunburst
[[moves]]
name = "Merciless Yoga"
name_ja = "ヨガマーシレス"
slug = "merciless-yoga"
characterId = 9
type = "super3"
hitCount = 1
blockType = "high"
input = "236236*k"

# Merciless Yoga (Critical Art)
[[moves]]
name = "Merciless Yoga (Critical Art)"
name_ja = "ヨガマーシレス (CA)"
slug = "merciless-yoga-ca"
characterId = 9
type = "super3"
hitCount = 1
blockType = "high"
input = "236236*k"

# Yoga Smash
[[moves]]
name = "Yoga Smash"
name_ja = "ヨガスマッシュ"
alternativeNames = ["Forward Throw"]
alternativeNames_ja = ["前投げ"]
slug = "yoga-smash"
characterId = 9
type = "throw"
input = "(lplk)"

# Yoga Throw
[[moves]]
name = "Yoga Throw"
name_ja = "ヨガスロー"
slug = "yoga-throw"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
characterId = 9
type = "throw"
hitCount = 1
input = "(5lplk)"

# Yoga Splash
[[moves]]
name = "Yoga Splash"
name_ja = "ヨガスプラッシュ"
slug = "yoga-splash"
characterId = 9
type = "throw"
hitCount = 1
input = "(2lplk)"
