# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱パン"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "ehonda-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中パン"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "ehonda-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強パン"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "ehonda-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱キック"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "ehonda-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中キック"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "ehonda-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強キック"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "ehonda-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "ehonda-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ中パン"]
slug = "ehonda-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強パン"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "ehonda-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱キック"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "ehonda-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "ehonda-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "ehonda-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱パン"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "ehonda-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jlp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中パン"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン"]
slug = "ehonda-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jmp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強パン"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "ehonda-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jhp"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱キック"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "ehonda-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jlk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中キック"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "ehonda-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jmk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強キック"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "ehonda-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 10
type = "normal"
hitCount = 1
blockType = "high"
input = "jhk"

# Hundred Hand Slap (Light)
[[moves]]
name = "Hundred Hand Slap (Light)"
name_ja = "百裂張り手 (弱)"
slug = "hundred-hand-slap-light"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "214lp"

# Hundred Hand Slap (Medium)
[[moves]]
name = "Hundred Hand Slap (Medium)"
name_ja = "百裂張り手 (中)"
slug = "hundred-hand-slap-medium"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "214mp"

# Hundred Hand Slap (Heavy)
[[moves]]
name = "Hundred Hand Slap (Heavy)"
name_ja = "百裂張り手 (強)"
slug = "hundred-hand-slap-heavy"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "214hp"

# Hundred Hand Slap (OD)
[[moves]]
name = "Hundred Hand Slap (OD)"
name_ja = "百裂張り手 (OD)"
slug = "hundred-hand-slap-od"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "214[pp]"

# Sumo Headbutt (Light)
[[moves]]
name = "Sumo Headbutt (Light)"
name_ja = "スーパー頭突き (弱)"
slug = "sumo-headbutt-light"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[4]6lp"

# Sumo Headbutt (Medium)
[[moves]]
name = "Sumo Headbutt (Medium)"
name_ja = "スーパー頭突き (中)"
slug = "sumo-headbutt-medium"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[4]6mp"

# Sumo Headbutt (Heavy)
[[moves]]
name = "Sumo Headbutt (Heavy)"
name_ja = "スーパー頭突き (強)"
slug = "sumo-headbutt-heavy"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[4]6hp"

# Sumo Headbutt (OD)
[[moves]]
name = "Sumo Headbutt (OD)"
name_ja = "スーパー頭突き (OD)"
slug = "sumo-headbutt-od"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[4]6[pp]"

# Sumo Smash (Light)
[[moves]]
name = "Sumo Smash (Light)"
name_ja = "スーパー百貫落とし (弱)"
slug = "sumo-smash-light"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[2]8lp"

# Sumo Smash (Medium)
[[moves]]
name = "Sumo Smash (Medium)"
name_ja = "スーパー百貫落とし (中)"
slug = "sumo-smash-medium"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[2]8mp"

# Sumo Smash (Heavy)
[[moves]]
name = "Sumo Smash (Heavy)"
name_ja = "スーパー百貫落とし (強)"
slug = "sumo-smash-heavy"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[2]8hp"

# Sumo Smash (OD)
[[moves]]
name = "Sumo Smash (OD)"
name_ja = "スーパー百貫落とし (OD)"
slug = "sumo-smash-od"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "[2]8[pp]"

# Oicho Throw (Light)
[[moves]]
name = "Oicho Throw (Light)"
name_ja = "大銀杏投げ (弱)"
slug = "oicho-throw-light"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "63214lp"

# Oicho Throw (Medium)
[[moves]]
name = "Oicho Throw (Medium)"
name_ja = "大銀杏投げ (中)"
slug = "oicho-throw-medium"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "63214mp"

# Oicho Throw (Heavy)
[[moves]]
name = "Oicho Throw (Heavy)"
name_ja = "大銀杏投げ (強)"
slug = "oicho-throw-heavy"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "63214hp"

# Oicho Throw (OD)
[[moves]]
name = "Oicho Throw (OD)"
name_ja = "大銀杏投げ (OD)"
slug = "oicho-throw-od"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "63214[pp]"

# Sumo Dash
[[moves]]
name = "Sumo Dash"
name_ja = "相撲ステップ"
slug = "sumo-dash"
characterId = 10
moveType = "action"
input = "236*k"

# Sumo Dash (OD)
[[moves]]
name = "Sumo Dash (OD)"
name_ja = "相撲ステップ (OD)"
slug = "sumo-dash-od"
characterId = 10
moveType = "action"
input = "236[kk]"

# Teppo Triple Slap
[[moves]]
name = "Teppo Triple Slap"
name_ja = "鉄砲"
slug = "teppo-triple-slap"
characterId = 10
moveType = "followUp"
hitCount = 1
blockType = "high"
input = "236*k>*p>*p"
parentSlug = "sumo-dash"

# Teppo Triple Slap (OD)
[[moves]]
name = "Teppo Triple Slap (OD)"
name_ja = "鉄砲 (OD)"
slug = "teppo-triple-slap-od"
characterId = 10
moveType = "followUp"
hitCount = 1
blockType = "high"
input = "236[kk]>*p>*p"
parentSlug = "sumo-dash-od"

# Taiho Cannon Lift
[[moves]]
name = "Taiho Cannon Lift"
name_ja = "大砲"
slug = "taiho-cannon-lift"
characterId = 10
followUp = "followUp"
hitCount = 1
blockType = "high"
input = "236*k>2*p"
parentSlug = "sumo-dash"

# Taiho Cannon Lift (OD)
[[moves]]
name = "Taiho Cannon Lift (OD)"
name_ja = "大砲 (OD)"
slug = "taiho-cannon-lift-od"
characterId = 10
followUp = "followUp"
hitCount = 1
blockType = "high"
input = "236[kk]>2*p"
parentSlug = "sumo-dash-od"

# Neko Damashi
[[moves]]
name = "Neko Damashi"
name_ja = "猫だまし"
slug = "neko-damashi"
characterId = 10
moveType = "special"
hitCount = 1
blockType = "high"
input = "22*p"

# Sumo Spirit
[[moves]]
name = "Sumo Spirit"
name_ja = "肩屋入り"
slug = "sumo-spirit"
characterId = 10
moveType = "action"
input = "22*k"

# Show of Force
[[moves]]
name = "Show of Force"
name_ja = "発揮爆砕"
slug = "show-of-force"
characterId = 10
moveType = "super1"
hitCount = 1
blockType = "high"
input = "236236*p"

# Ultimate Killer Head Ram
[[moves]]
name = "Ultimate Killer Head Ram"
name_ja = "スーパー鬼無双"
slug = "ultimate-killer-head-ram"
characterId = 10
moveType = "super2"
hitCount = 1
blockType = "high"
input = "[4]646*k"

# The Final Bout
[[moves]]
name = "The Final Bout"
name_ja = "千秋楽"
slug = "the-final-bout"
characterId = 10
moveType = "super3"
hitCount = 1
blockType = "high"
input = "214214*p"

# Harai Kick
[[moves]]
name = "Harai Kick"
name_ja = "払い蹴り"
slug = "harai-kick"
characterId = 10
moveType = "commandNormal"
hitCount = 1
blockType = "high"
input = "6hk"

# Power Stomp
[[moves]]
name = "Power Stomp"
name_ja = "力足"
slug = "power-stomp"
characterId = 10
moveType = "commandNormal"
hitCount = 1
blockType = "high"
input = "3hk"

# Flying Sumo Press
[[moves]]
name = "Flying Sumo Press"
name_ja = "フライングスモウプレス"
slug = "flying-sumo-press"
characterId = 10
moveType = "commandNormal"
hitCount = 1
blockType = "high"
input = "2mk"

# Double Slaps
[[moves]]
name = "Double Slaps"
name_ja = "連ね張り手"
slug = "double-slaps"
characterId = 10
moveType = "targetCombo"
hitCount = 2
blockType = "high"
input = "5lp>5mp"

# Toko Shizume
[[moves]]
name = "Toko Shizume"
name_ja = "地鎮"
slug = "toko-shizume"
characterId = 10
moveType = "targetCombo"
hitCount = 1
blockType = "high"
input = "5mp>3hk"

# Saba Ori
[[moves]]
name = "Saba Ori"
name_ja = "さば折り"
alternativeNames = ["Forward Throw"]
alternativeNames_ja = ["前投げ"]
slug = "saba-ori"
characterId = 10
hitCount = 1
blockType = "high"
input = "[lplk]"

# Tawara Throw
[[moves]]
name = "Tawara Throw"
name_ja = "俵投げ"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
slug = "tawara-throw"
characterId = 10
hitCount = 1
blockType = "high"
input = "[4lplk]"
