# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱P"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "jamie-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
startup = 5
active = [5, 6]
recovery = 7
cancel = "C"
damage = 300
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 5

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中P"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "jamie-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

startup = 8
active = [8, 11]
recovery = 14
damage = 600
superArt = 500

[moves.frameAdvantage]
hit = 5
block = 1

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -6000

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強P"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "jamie-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"
notes = ["Can be canceled until the 1st active frame", "Forces a juggle state when hitting a mid-air opponent"]
notes_ja = ["持続の1F目までキャンセル可", "空中ヒット時吹き飛びやられ"]

startup = 5
active = [5, 7, 12, 14]
recovery = 20
cancel = "C"
damage = 900
superArt = 1600

[moves.frameAdvantage]
hit = 1
block = -3

[moves.driveGauge]
onHit = 2000
onBlock = -5000
onPunishCounter = -8000

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱K"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "jamie-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 5
active = [5, 6]
recovery = 11
cancel = "C"
damage = 300
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 3
block = -1

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中K"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "jamie-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

startup = 10
active = [10, 12]
recovery = 17
cancel = "C"
damage = 600
superArt = 700

[moves.frameAdvantage]
hit = 1
block = -3

[moves.driveGauge]
onHit = 1500
onBlock = -3000
onPunishCounter = -4000

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強K"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "jamie-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

notes = ["Produces a crumple stun on Punish Counter", "Forces a juggle satte when hitting a mid-air opponent"]
notes_ja = ["パニッシュカウンター時膝くずれ", "空中ヒット時吹き飛びやられ"]

startup = 15
active = [15, 17]
recovery = 21
cancel = "C"
damage = 800
superArt = 1000

[moves.frameAdvantage]
hit = 1
block = -5

[moves.driveGauge]
onHit = 3000
onBlock = -4000
onPunishCounter = -10000

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "jamie-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 4
active = [4, 5]
recovery = 9
cancel = "C"
damage = 250
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 5
block = -1

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中P"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ中P"]
slug = "jamie-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

startup = 6
active = [6, 8]
recovery = 13
cancel = "C"
damage = 600
superArt = 500

[moves.frameAdvantage]
hit = 3

[moves.driveGauge]
onHit = 1500
onBlock = -3000
onPunishCounter = -4000

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強P"
alternativeNames = ["Crouching fierce"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "jamie-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

notes = ["Can be canceled until the 2nd active frame"]
notes_ja = ["持続の2F目までキャンセル可"]

startup = 9
active = [9, 13]
recovery = 23
cancel = "C"
damage = 900
superArt = 1000

[moves.frameAdvantage]
hit = 0
block = -8

[moves.driveGauge]
onHit = 2500
onBlock = -5000
onPunishCounter = -7000

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱K"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "jamie-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 5
active = [5, 6]
recovery = 11
damage = 200
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 1
block = -3

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "jamie-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

startup = 7
active = [7, 9]
recovery = 18
cancel = "C"
damage = 500
scaling = ["Starter scaling 20%"]
scaling_ja = ["始動補正20%"]
superArt = 600

[moves.frameAdvantage]
hit = -1
block = -6

[moves.driveGauge]
onHit = 1000
onBlock = -2000
onPunishCounter = -4000

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強K"
alternativeNames = ["Crouching roundhouse"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "jamie-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

properties = ["knockdown"]
notes = ["Hard knockdown when hitting an opponent standing on the ground", "Knockdown time extended when attack lands as a counter or Punish Counter", "Forces a juggle state when hitting a mid-air opponent"]
notes_ja = ["地上ヒット時ハードノックダウン", "カウンター/パニッシュカウンター時ダウン時間延長", "空中ヒット時吹き飛びやられ"]

startup = 9
active = [9, 10, 13, 15]
recovery = 28
damage = 800
superArt = 1000

[moves.frameAdvantage]
block = -10

[moves.driveGauge]
onHit = 3000
onBlock = -2000
onPunishCounter = -5000

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱P"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "jamie-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"
notes = ["Has cross-up attack properties"]
notes_ja = ["めくり性能"]

startup = 5
active = [5, 13]
postLandingRecovery = 3
damage = 300
superArt = 300

[moves.driveGauge]
onHit = 500
onBlock = -1500
onPunishCounter = -2000

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中P"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン", "ジャンプチュウパン"]
slug = "jamie-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"
notes = ["Forces a juggle state when hitting a mid-air opponent"]
notes_ja = ["空中ヒット時吹き飛びやられ"]

startup = 7
active = [7, 10]
postLandingRecovery = 3
cancel = "C"
damage = 700
superArt = 500

[moves.driveGauge]
onHit = 1000
onBlock = -2500
onPunishCounter = -4000

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強P"
alternativeNames = ["Jumping fierce"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "jamie-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 2
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hp"
notes = ["Forces a slam knockdown when hitting a mid-air opponent"]
notes_ja = ["空中ヒット時叩きつけダウン"]

startup = 10
active = [10, 15]
postLandingRecovery = 3
damage = 800
superArt = 1000

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -5000

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱K"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "jamie-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>lk"

startup = 6
active = [6, 11]
postLandingRecovery = 3
damage = 300
superArt = 300

[moves.driveGauge]
onHit = 500
onBlock = -1500
onPunishCounter = -2000

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中K"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "jamie-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>mk"
notes = ["Has cross-up attack properties"]
notes_ja = ["めくり性能"]

startup = 7
active = [7, 12]
postLandingRecovery = 3
damage = 500
superArt = 500

[moves.driveGauge]
onHit = 1000
onBlock = -2500
onPunishCounter = -4000

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強K"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "jamie-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 2
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hk"

startup = 8
active = [8, 10, 16, 19]
postLandingRecovery = 3
damage = 800
superArt = 2000

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -2500

# Tensei Kick
[[moves]]
name = "Tensei Kick"
name_ja = "天晴脚"
slug = "tensei-kick"
characterId = 2
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "(kk)"

# Phantom Sway
[[moves]]
name = "Phantom Sway"
name_ja = "幻酔舞"
slug = "phantom-sway"
characterId = 2
type = "commandNormal"
hitCount = 3
blockType = "high"
input = "4hk>hk>*p"

# Falling Star Kick
[[moves]]
name = "Falling Star Kick"
name_ja = "落星脚"
slug = "falling-star-kick"
characterId = 2
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "6mk"

# Hermit's Elbow
[[moves]]
name = "Hermit's Elbow"
name_ja = "仙姑肘"
slug = "hermits-elbow"
characterId = 2
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4hp"

# Sensei Kick
[[moves]]
name = "Sensei Kick"
name_ja = "旋影脚"
slug = "sensei-kick"
characterId = 2
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "6hk"

# Bitter Strikes
[[moves]]
name = "Bitter Strikes"
name_ja = "苦撃"
slug = "bitter-strikes"
characterId = 2
type = "commandNormal"
hitCount = 3
blockType = "high"
input = "5lp>5lk>5mp"
notes = ["Requires drink level 1."]
notes_ja = ["酔いレベル1必要"]

# Full Moon Kick
[[moves]]
name = "Full Moon Kick"
name_ja = "円月脚"
slug = "full-moon-kick"
characterId = 2
type = "commandNormal"
hitCount = 3
blockType = "high"
input = "6mk>5mk>5*p"
notes = ["Requires drink level 2."]
notes_ja = ["酔いレベル2必要"]

# Intoxicated Assault
[[moves]]
name = "Intoxicated Assault"
name_ja = "酩酊襲"
slug = "intoxicated-assault"
characterId = 2
type = "commandNormal"
hitCount = 3
blockType = "high"
input = "4hp>5hp>5*k"
notes = ["Requires drink level 3."]
notes_ja = ["酔いレベル3必要"]

# Ransui Haze
[[moves]]
name = "Ransui Haze"
name_ja = "乱酔旋"
slug = "ransui-haze"
characterId = 2
type = "commandNormal"
hitCount = 3
blockType = "high"
input = "6hk>5hk>5*p"
notes = ["Requires drink level 4."]
notes_ja = ["酔いレベル4必要"]

# The Devil Inside
[[moves]]
name = "The Devil Inside"
name_ja = "魔身"
slug = "the-devil-inside"
characterId = 2
type = "special"
input = "22*p"

# Freeflow Strikes (Light)
[[moves]]
name = "Freeflow Strikes (Light)"
alternateNames = ["Rekkas"]
name_ja = "流酔拳 (弱)"
alternateNames_ja = ["烈火"]
slug = "freeflow-strikes-light"
characterId = 2
type = "special"
blockType = "high"
input = "236lp>6*p>6*p"

# Freeflow Strikes (Medium)
[[moves]]
name = "Freeflow Strikes (Medium)"
alternateNames = ["Rekkas"]
name_ja = "流酔拳 (中)"
alternateNames_ja = ["烈火"]
slug = "freeflow-strikes-medium"
characterId = 2
type = "special"
blockType = "high"
input = "236mp>6*p>6*p"

# Freeflow Strikes (Heavy)
[[moves]]
name = "Freeflow Strikes (Heavy)"
alternateNames = ["Rekkas"]
name_ja = "流酔拳 (強)"
alternateNames_ja = ["烈火"]
slug = "freeflow-strikes-heavy"
characterId = 2
type = "special"
blockType = "high"
input = "236hp>6*p>6*p"

# Freeflow Strikes (OD)
[[moves]]
name = "Freeflow Strikes (OD)"
alternateNames = ["Rekkas"]
name_ja = "流酔拳 (OD)"
alternateNames_ja = ["烈火"]
slug = "freeflow-strikes-od"
characterId = 2
type = "special"
blockType = "high"
input = "236(pp)>6*p>6*p"

# Freeflow Kicks (Light)
[[moves]]
name = "Freeflow Kicks (Light)"
alternateNames = ["Rekkas"]
name_ja = "流酔脚 (弱)"
alternateNames_ja = ["烈火"]
slug = "freeflow-kicks-light"
characterId = 2
type = "special"
blockType = "high"
input = "236lp>6*k>6*k"

# Freeflow Kicks (Medium)
[[moves]]
name = "Freeflow Kicks (Medium)"
alternateNames = ["Rekkas"]
name_ja = "流酔脚 (中)"
alternateNames_ja = ["烈火"]
slug = "freeflow-kicks-medium"
characterId = 2
type = "special"
blockType = "high"
input = "236mp>6*k>6*k"

# Freeflow Kicks (Heavy)
[[moves]]
name = "Freeflow Kicks (Heavy)"
alternateNames = ["Rekkas"]
name_ja = "流酔脚 (強)"
alternateNames_ja = ["烈火"]
slug = "freeflow-kicks-heavy"
characterId = 2
type = "special"
blockType = "high"
input = "236hp>6*k>6*k"

# Freeflow Kicks (OD)
[[moves]]
name = "Freeflow Kicks (OD)"
alternateNames = ["Rekkas"]
name_ja = "流酔脚 (OD)"
alternateNames_ja = ["烈火"]
slug = "freeflow-kicks-od"
characterId = 2
type = "special"
blockType = "high"
input = "236(pp)>6*k>6*k"

# Swagger Step (Light)
[[moves]]
name = "Swagger Step (Light)"
name_ja = "酔疾歩 (弱)"
slug = "swagger-step-light"
characterId = 2
type = "special"
blockType = "high"
input = "214lp"

# Swagger Step (Medium)
[[moves]]
name = "Swagger Step (Medium)"
name_ja = "酔疾歩 (中)"
slug = "swagger-step-medium"
characterId = 2
type = "special"
blockType = "high"
input = "214mp"

# Swagger Step (Heavy)
[[moves]]
name = "Swagger Step (Heavy)"
name_ja = "酔疾歩 (強)"
slug = "swagger-step-heavy"
characterId = 2
type = "special"
blockType = "high"
input = "214hp"

# Swagger Step (OD)
[[moves]]
name = "Swagger Step (OD)"
name_ja = "酔疾歩 (OD)"
slug = "swagger-step-od"
characterId = 2
type = "special"
blockType = "high"
input = "214(pp)"

# Swagger Hermit Punch
[[moves]]
name = "Swagger Hermit Punch"
name_ja = "疾歩仙掌"
slug = "swagger-hermit-punch"
characterId = 2
type = "special"
blockType = "high"
input = "214*p>6*p"
parentSlugs = ["swagger-step"]
notes = ["Requires drink level 4."]
notes_ja = ["酔いレベル4必要"]

# Swagger Hermit Punch (OD)
[[moves]]
name = "Swagger Hermit Punch (OD)"
name_ja = "疾歩仙掌 (OD)"
slug = "swagger-hermit-punch-od"
characterId = 2
type = "special"
blockType = "high"
input = "214(pp)>6*p"
parentSlugs = ["swagger-step-od"]
notes = ["Requires drink level 4."]
notes_ja = ["酔いレベル4必要"]

# Arrow Kick (Light)
[[moves]]
name = "Arrow Kick (Light)"
name_ja = "張弓腿 (弱)"
slug = "arrow-kick-light"
characterId = 2
type = "special"
blockType = "high"
input = "623lk"

# Arrow Kick (Medium)
[[moves]]
name = "Arrow Kick (Medium)"
name_ja = "張弓腿 (中)"
slug = "arrow-kick-medium"
characterId = 2
type = "special"
blockType = "high"
input = "623mk"

# Arrow Kick (Heavy)
[[moves]]
name = "Arrow Kick (Heavy)"
name_ja = "張弓腿 (強)"
slug = "arrow-kick-heavy"
characterId = 2
type = "special"
blockType = "high"
input = "623hk"

# Arrow Kick (OD)
[[moves]]
name = "Arrow Kick (OD)"
name_ja = "張弓腿 (OD)"
slug = "arrow-kick-od"
characterId = 2
type = "special"
blockType = "high"
input = "623(pp)"

# Luminous Dive Kick
[[moves]]
name = "Luminous Dive Kick"
name_ja = "無影蹴"
slug = "luminous-dive-kick"
characterId = 2
type = "special"
blockType = "high"
input = "j>214*k"

# Luminous Dive Kick (OD)
[[moves]]
name = "Luminous Dive Kick (OD)"
name_ja = "無影蹴 (OD)"
slug = "luminous-dive-kick-od"
characterId = 2
type = "special"
blockType = "high"
input = "j>214(kk)"
notes = ["Requires drink level 1."]
notes_ja = ["酔いレベル1必要"]

# Bakkai
[[moves]]
name = "Bakkai"
name_ja = "爆廻"
slug = "bakkai"
characterId = 2
type = "special"
blockType = "high"
input = "236*k"
notes = ["Requires drink level 2."]
notes_ja = ["酔いレベル2必要"]

# Tenshin
[[moves]]
name = "Tenshin"
name_ja = "点辰"
slug = "tenshin"
characterId = 2
type = "commandThrow"
blockType = "high"
input = "63214*k"
notes = ["Requires drink level 3."]
notes_ja = ["酔いレベル3必要"]

# Breakin'
[[moves]]
name = "Breakin'"
name_ja = "戦麗禽"
slug = "breakin"
characterId = 2
type = "super1"
blockType = "high"
input = "236236*k"

# The Devil's Song
[[moves]]
name = "The Devil's Song"
name_ja = "絶唱魔身"
slug = "the-devils-song"
characterId = 2
type = "super2"
blockType = "high"
input = "214214*p"

# Getsuga Saiho
[[moves]]
name = "Getsuga Saiho"
name_ja = "月牙叉炮"
slug = "getsuga-saiho"
characterId = 2
type = "super3"
blockType = "high"
input = "236236*p"

# Getsuga Saiho (Critical Art)
[[moves]]
name = "Getsuga Saiho (Critical Art)"
name_ja = "月牙叉炮 (CA)"
slug = "getsuga-saiho-ca"
characterId = 2
type = "super3"
blockType = "high"
input = "236236*p"

# Back Shaver
[[moves]]
name = "Back Shaver"
name_ja = "背剪手"
slug = "back-shaver"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
characterId = 2
type = "throw"
blockType = "high"
input = "(4lplk)"

# Wheel Punch
[[moves]]
name = "Wheel Punch"
name_ja = "車輪拳"
slug = "wheel-punch"
alternativeNames = ["Forward Throw"]
alternativeNames_ja = ["前投げ"]
characterId = 2
type = "throw"
blockType = "high"
input = "(lplk)"
