# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱P"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "kimberly-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中P"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "kimberly-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強P"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "kimberly-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱K"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "kimberly-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中K"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "kimberly-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強K"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "kimberly-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "kimberly-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中P"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ中P"]
slug = "kimberly-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強P"
alternativeNames = ["Crouching fierce"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "kimberly-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱K"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "kimberly-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "kimberly-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強K"
alternativeNames = ["Crouching roundhouse"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "kimberly-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱P"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "kimberly-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中P"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン", "ジャンプチュウパン"]
slug = "kimberly-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強P"
alternativeNames = ["Jumping fierce"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "kimberly-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 5
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hp"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱K"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "kimberly-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>lk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中K"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "kimberly-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>mk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強K"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "kimberly-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 5
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hk"

# Water Slicer Slide
[[moves]]
name = "Water Slicer Slide"
name_ja = "水切り蹴り"
slug = "water-slicer-slide"
characterId = 5
type = "commandNormal"
hitCount = 1
blockType = "low"
input = "3mk"

# Windmill Kick
[[moves]]
name = "Windmill Kick"
name_ja = "風車"
slug = "windmill-kick"
characterId = 5
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4hk"

# Hisen Kick
[[moves]]
name = "Hisen Kick"
name_ja = "飛箭蹴"
slug = "hisen-kick"
characterId = 5
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "6hk"

# Step Up
[[moves]]
name = "Step Up"
name_ja = "矢来越え"
slug = "step-up"
characterId = 5
type = "commandNormal"
input = "6hk>7|8|9"
parentSlugs = ["hisen-kick"]

# Elbow Drop
[[moves]]
name = "Elbow Drop"
name_ja = "肘落とし"
slug = "elbow-drop"
characterId = 5
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "j>2mp"

# Bushin Tiger Fangs
[[moves]]
name = "Bushin Tiger Fangs"
name_ja = "武神虎連牙"
slug = "bushin-tiger-fangs"
characterId = 5
type = "targetCombo"
hitCount = 2
blockType = "high"
input = "mp>hp"

# Bushin Prism Strikes
[[moves]]
name = "Bushin Prism Strikes"
name_ja = "武神天架拳"
slug = "bushin-prism-strikes"
characterId = 5
type = "targetCombo"
hitCount = 3
blockType = "high"
input = "lp>mp>hp>hk"

# Bushin Hellchain
[[moves]]
name = "Bushin Hellchain"
name_ja = "武神獄鎖拳"
slug = "bushin-hellchain"
characterId = 5
type = "targetCombo"
hitCount = 3
blockType = "high"
input = "lp>mp>2hp>2hk"

# Bushin Hellchain Throw
[[moves]]
name = "Bushin Hellchain Throw"
name_ja = "武神獄鎖投げ"
slug = "bushin-hellchain-throw"
characterId = 5
type = "targetCombo"
hitCount = 4
blockType = "high"
input = "lp>mp>2hp>2hk"

# Bunshin Senpu-kyaku (Light)
[[moves]]
name = "Bunshin Senpu-kyaku (Light)"
name_ja = "武神旋風脚 (弱)"
slug = "bunshin-senpukyaku-light"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "214lk"

# Bunshin Senpu-kyaku (Medium)
[[moves]]
name = "Bunshin Senpu-kyaku (Medium)"
name_ja = "武神旋風脚 (中)"
slug = "bunshin-senpukyaku-medium"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "214mk"

# Bunshin Senpu-kyaku (Heavy)
[[moves]]
name = "Bunshin Senpu-kyaku (Heavy)"
name_ja = "武神旋風脚 (強)"
slug = "bunshin-senpukyaku-heavy"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "214hk"

# Bunshin Senpu-kyaku (OD)
[[moves]]
name = "Bunshin Senpu-kyaku (OD)"
name_ja = "武神旋風脚 (OD)"
slug = "bunshin-senpukyaku-od"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "214(kk)"

# Aerial Bunshin Senpu-kyaku (Light)
[[moves]]
name = "Aerial Bunshin Senpu-kyaku (Light)"
name_ja = "空中武神旋風脚 (弱)"
slug = "aerial-bunshin-senpukyaku-light"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "j>214lk"

# Aerial Bunshin Senpu-kyaku (Medium)
[[moves]]
name = "Aerial Bunshin Senpu-kyaku (Medium)"
name_ja = "空中武神旋風脚 (中)"
slug = "aerial-bunshin-senpukyaku-medium"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "j>214mk"

# Aerial Bunshin Senpu-kyaku (Heavy)
[[moves]]
name = "Aerial Bunshin Senpu-kyaku (Heavy)"
name_ja = "空中武神旋風脚 (強)"
slug = "aerial-bunshin-senpukyaku-heavy"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "j>214hk"

# Aerial Bunshin Senpu-kyaku (OD)
[[moves]]
name = "Aerial Bunshin Senpu-kyaku (OD)"
name_ja = "空中武神旋風脚 (OD)"
slug = "aerial-bunshin-senpukyaku-od"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "j>214(kk)"

# Sprint
[[moves]]
name = "Sprint"
name_ja = "疾駆け"
slug = "sprint"
characterId = 5
type = "special"
input = "236*k"

# Sprint (OD)
[[moves]]
name = "Sprint (OD)"
name_ja = "疾駆け (OD)"
slug = "sprint-od"
characterId = 5
type = "special"
input = "236(kk)"

# Emergency Stop
[[moves]]
name = "Emergency Stop"
name_ja = "急停止"
slug = "kimberly-emergency-stop"
characterId = 5
type = "special"
input = "236*k>*p"
parentSlugs = ["sprint"]

# Emergency Stop (OD)
[[moves]]
name = "Emergency Stop (OD)"
name_ja = "急停止 (OD)"
slug = "kimberly-emergency-stop-od"
characterId = 5
type = "special"
input = "236(kk)>*p"
parentSlugs = ["sprint-od"]

# Torso Cleaver
[[moves]]
name = "Torso Cleaver"
name_ja = "胴刎ね"
slug = "torso-cleaver"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "236*k>*k"
parentSlugs = ["sprint"]

# Torso Cleaver (OD)
[[moves]]
name = "Torso Cleaver (OD)"
name_ja = "胴刎ね (OD)"
slug = "torso-cleaver-od"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "236(kk)>*k"
parentSlugs = ["sprint-od"]

# Shadow Slide
[[moves]]
name = "Shadow Slide"
name_ja = "影すくい"
slug = "shadow-slide"
characterId = 5
type = "special"
hitCount = 1
blockType = "low"
input = "236*k>mk"
parentSlugs = ["sprint"]

# Shadow Slide (OD)
[[moves]]
name = "Shadow Slide (OD)"
name_ja = "影すくい (OD)"
slug = "shadow-slide-od"
characterId = 5
type = "special"
hitCount = 1
blockType = "low"
input = "236(kk)>mk"
parentSlugs = ["sprint-od"]

# Neck Hunter
[[moves]]
name = "Neck Hunter"
name_ja = "首狩り"
slug = "neck-hunter"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "236*k>hk"
parentSlugs = ["sprint"]

# Neck Hunter (OD)
[[moves]]
name = "Neck Hunter (OD)"
name_ja = "首狩り (OD)"
slug = "neck-hunter-od"
characterId = 5
type = "special"
hitCount = 1
blockType = "high"
input = "236(kk)>hk"
parentSlugs = ["sprint-od"]

# Arc Step
[[moves]]
name = "Arc Step"
name_ja = "アークステップ"
slug = "arc-step"
characterId = 5
type = "special"
input = "236*k"
parentSlugs = ["sprint"]
notes = ["Auto when close."]
notes_ja = ["近距離で自動発動"]

# Arc Step (OD)
[[moves]]
name = "Arc Step (OD)"
name_ja = "アークステップ (OD)"
slug = "arc-step-od"
characterId = 5
type = "special"
input = "236(kk)"
parentSlugs = ["sprint-od"]
notes = ["Auto when close."]
notes_ja = ["近距離で自動発動"]

# Bushin Izuna Otoshi
[[moves]]
name = "Bushin Izuna Otoshi"
name_ja = "武神飯綱落とし"
slug = "bushin-izuna-otoshi"
characterId = 5
type = "special"
input = "*p"
parentSlugs = ["arc-step"]

# Bushin Hojin Kick
[[moves]]
name = "Bushin Hojin Kick"
name_ja = "武神鉾刃脚"
slug = "bushin-hojin-kick"
characterId = 5
type = "special"
input = "*k"
parentSlugs = ["arc-step"]

# Vagabond Edge (Light)
[[moves]]
name = "Vagabond Edge (Light)"
name_ja = "逆転一文字 (弱)"
slug = "vagabond-edge-light"
characterId = 5
type = "special"
input = "236*p"

# Vagabond Edge (Medium)
[[moves]]
name = "Vagabond Edge (Medium)"
name_ja = "逆転一文字 (中)"
slug = "vagabond-edge-medium"
characterId = 5
type = "special"
input = "236mp"

# Vagabond Edge (Heavy)
[[moves]]
name = "Vagabond Edge (Heavy)"
name_ja = "逆転一文字 (強)"
slug = "vagabond-edge-heavy"
characterId = 5
type = "special"
input = "236hp"

# Vagabond Edge (OD)
[[moves]]
name = "Vagabond Edge (OD)"
name_ja = "逆転一文字 (OD)"
slug = "vagabond-edge-od"
characterId = 5
type = "special"
input = "236(kk)"

# Hidden Variable
[[moves]]
name = "Hidden Variable"
name_ja = "彩隠形"
slug = "hidden-variable"
characterId = 5
type = "special"
input = "214*p"

# Hidden Variable (OD)
[[moves]]
name = "Hidden Variable (OD)"
name_ja = "彩隠形 (OD)"
slug = "hidden-variable-od"
characterId = 5
type = "special"
input = "214(pp)"

# Genius at Play
[[moves]]
name = "Genius at Play"
name_ja = "召雷細工"
slug = "genius-at-play"
characterId = 5
type = "special"
input = "22*p"
notes = ["When shuriken count is zero."]
notes_ja = ["手裏剣が0の時"]

# Genius at Play (OD)
[[moves]]
name = "Genius at Play (OD)"
name_ja = "召雷細工 (OD)"
slug = "genius-at-play-od"
characterId = 5
type = "special"
input = "22(pp)"
notes = ["When shuriken count is zero."]
notes_ja = ["手裏剣が0の時"]

# Shuriken Bomb
[[moves]]
name = "Shuriken Bomb"
name_ja = "細工手裏剣"
slug = "shuriken-bomb"
characterId = 5
type = "special"
input = "22*p"
notes = ["Strength used affects the distance."]
notes_ja = ["強さで飛距離が変化"]
parentSlugs = ["genius-at-play"]

# Shuriken Bomb Spread
[[moves]]
name = "Shuriken Bomb Spread"
name_ja = "乱れ細工手裏剣"
slug = "shuriken-bomb-spread"
characterId = 5
type = "special"
input = "22(pp)"
notes = ["Strength used affects the distance."]
notes_ja = ["強さで飛距離が変化"]
parentSlugs = ["genius-at-play-od"]

# Nue Twister
[[moves]]
name = "Nue Twister"
name_ja = "荒鶴捻り"
slug = "nue-twister"
characterId = 5
type = "special"
input = "j>236*p"

# Nue Twister (OD)
[[moves]]
name = "Nue Twister (OD)"
name_ja = "荒鶴捻り (OD)"
slug = "nue-twister-od"
characterId = 5
type = "special"
input = "j>236(pp)"

# Bushin Beats
[[moves]]
name = "Bushin Beats"
name_ja = "武神乱舞"
slug = "bushin-beats"
characterId = 5
type = "super1"
input = "236236*k"

# Bushin Thunderous Beats
[[moves]]
name = "Bushin Thunderous Beats"
name_ja = "武神雷鳴乱舞"
slug = "bushin-thunderous-beats"
characterId = 5
type = "super1"
input = "236236*k"
notes = ["With 1+ shuriken."]
notes_ja = ["手裏剣が1本以上"]

# Bushin Scramble
[[moves]]
name = "Bushin Scramble"
name_ja = "武神天翔亢竜"
slug = "bushin-scramble"
characterId = 5
type = "super2"
input = "214214*p"

# Soaring Bushin Scramble
[[moves]]
name = "Soaring Bushin Scramble"
name_ja = "空中武神天翔亢竜"
slug = "soaring-bushin-scramble"
characterId = 5
type = "super2"
input = "j>214214*p"

# Bushin Ninjastar Cypher
[[moves]]
name = "Bushin Ninjastar Cypher"
name_ja = "武神顕現神楽"
slug = "bushin-ninjastar-cypher"
characterId = 5
type = "super3"
input = "236236*p"

# Bushin Ninjastar Cypher (Critical Art)
[[moves]]
name = "Bushin Ninjastar Cypher (Critical Art)"
name_ja = "武神顕現神楽 (CA)"
slug = "bushin-ninjastar-cypher-ca"
characterId = 5
type = "super3"
input = "236236*p"

# Ripcord Throw
[[moves]]
name = "Ripcord Throw"
name_ja = "縄掛背負い"
alternativeNames = ["Forward throw"]
alternativeNames_ja = ["前投げ"]
slug = "ripcord-throw"
characterId = 5
type = "throw"
input = "(lplk)"

# Bell Ringer
[[moves]]
name = "Bell Ringer"
name_ja = "鐘打巴"
alternativeNames = ["Back throw"]
alternativeNames_ja = ["後ろ投げ"]
slug = "bell-ringer"
characterId = 5
type = "throw"
input = "(4lplk)"
