# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱P"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "lily-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中P"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "lily-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強P"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "lily-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱K"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "lily-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中K"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "lily-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強K"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "lily-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "lily-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ中P"]
slug = "lily-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強P"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "lily-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱K"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "lily-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "lily-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "lily-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱P"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "lily-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中P"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中P"]
slug = "lily-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強P"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "lily-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hp"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱K"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "lily-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中K"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "lily-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強K"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "lily-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 16
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hk"

# Condor Wind (Light)
[[moves]]
name = "Condor Wind (Light)"
name_ja = "コンドルウィンド（弱）"
slug = "condor-wind-light"
characterId = 16
type = "special"
blockType = "high"
input = "214lp"
properties = ["chargeable", "stockIncrement"]

# Condor Wind (Medium)
[[moves]]
name = "Condor Wind (Medium)"
name_ja = "コンドルウィンド（中）"
slug = "condor-wind-medium"
characterId = 16
type = "special"
blockType = "high"
input = "214mp"
properties = ["chargeable", "stockIncrement"]

# Condor Wind (Heavy)
[[moves]]
name = "Condor Wind (Heavy)"
name_ja = "コンドルウィンド（強）"
slug = "condor-wind-heavy"
characterId = 16
type = "special"
blockType = "high"
input = "214hp"
properties = ["chargeable", "stockIncrement"]

# Condor Wind (OD)
[[moves]]
name = "Condor Wind (OD)"
name_ja = "コンドルウィンド (OD)"
slug = "condor-wind-od"
characterId = 16
type = "special"
blockType = "high"
input = "214(kk)"
properties = ["chargeable", "stockIncrement"]

# Condor Spire (Light)
[[moves]]
name = "Condor Spire (Light)"
name_ja = "コンドルスパイア (弱)"
slug = "condor-spire-light"
characterId = 16
type = "special"
blockType = "high"
input = "236lk"
properties = ["stockDecrement"]

# Condor Spire (Medium)
[[moves]]
name = "Condor Spire (Medium)"
name_ja = "コンドルスパイア (中)"
slug = "condor-spire-medium"
characterId = 16
type = "special"
blockType = "high"
input = "236mk"
properties = ["stockDecrement"]

# Condor Spire (Heavy)
[[moves]]
name = "Condor Spire (Heavy)"
name_ja = "コンドルスパイア (強)"
slug = "condor-spire-heavy"
characterId = 16
type = "special"
blockType = "high"
input = "236hk"
properties = ["stockDecrement"]

# Condor Spire (OD)
[[moves]]
name = "Condor Spire (OD)"
name_ja = "コンドルスパイア (OD)"
slug = "condor-spire-od"
characterId = 16
type = "special"
blockType = "high"
input = "236(kk)"
properties = ["stockDecrement"]

# Tomahawk Buster (Light)
[[moves]]
name = "Tomahawk Buster (Light)"
name_ja = "トマホークバスター (弱)"
slug = "tomahawk-buster-light"
characterId = 16
type = "special"
blockType = "high"
input = "623lp"
properties = ["stockDecrement"]

# Tomahawk Buster (Medium)
[[moves]]
name = "Tomahawk Buster (Medium)"
name_ja = "トマホークバスター (中)"
slug = "tomahawk-buster-medium"
characterId = 16
type = "special"
blockType = "high"
input = "623mp"
properties = ["stockDecrement"]

# Tomahawk Buster (Heavy)
[[moves]]
name = "Tomahawk Buster (Heavy)"
name_ja = "トマホークバスター (強)"
slug = "tomahawk-buster-heavy"
characterId = 16
type = "special"
blockType = "high"
input = "623hp"
properties = ["stockDecrement"]

# Tomahawk Buster (OD)
[[moves]]
name = "Tomahawk Buster (OD)"
name_ja = "トマホークバスター (OD)"
slug = "tomahawk-buster-od"
characterId = 16
type = "special"
blockType = "high"
input = "623(pp)"
properties = ["stockDecrement"]
cancelsInto = ["condor-dive-od"]
cancel = "*"

# Condor Dive
[[moves]]
name = "Condor Dive"
name_ja = "コンドルダイブ"
slug = "condor-dive"
characterId = 16
type = "special"
blockType = "high"
input = "{8|9}+(pp)"

# Condor Dive (OD)
[[moves]]
name = "Condor Dive (OD)"
name_ja = "コンドルダイブ (OD)"
slug = "condor-dive-od"
characterId = 16
type = "special"
blockType = "high"
input = "{8|9}+(ppp)"

# Mexican Typhoon
[[moves]]
name = "Mexican Typhoon"
name_ja = "メキシカンタイフーン"
slug = "mexican-typhoon"
characterId = 16
type = "commandThrow"
blockType = "high"
input = "{360}+*p"

# Breezing Hawk
[[moves]]
name = "Breezing Hawk"
name_ja = "ブリージングホーク"
slug = "breezing-hawk"
characterId = 16
type = "super1"
blockType = "high"
input = "236236*p"

# Thunderbird
[[moves]]
name = "Thunderbird"
name_ja = "サンダーバード"
slug = "thunderbird"
characterId = 16
type = "super2"
blockType = "high"
input = "236236*k"
properties = ["stockDecrement"]

# Soaring Thunderbird
[[moves]]
name = "Soaring Thunderbird"
name_ja = "スカイサンダーバード"
slug = "soaring-thunderbird"
characterId = 16
type = "super2"
blockType = "high"
input = "j>236236*k"
properties = ["stockDecrement"]

# Raging Typhoon
[[moves]]
name = "Raging Typhoon"
name_ja = "レイジングタイフーン"
slug = "raging-typhoon"
characterId = 16
type = "super3"
blockType = "high"
input = "214214*p"

# Raging Typhoon (Critical Art)
[[moves]]
name = "Raging Typhoon (Critical Art)"
name_ja = "レイジングタイフーン (CA)"
slug = "raging-typhoon-ca"
characterId = 16
type = "super3"
blockType = "high"
input = "214214*p"

# Ridge Thrust
[[moves]]
name = "Ridge Thrust HK"
name_ja = "スラストリッジ"
slug = "ridge-thrust-hk"
characterId = 16
type = "commandNormal"
blockType = "high"
input = "3hk"

# Horn Breaker
[[moves]]
name = "Horn Breaker HP"
name_ja = "ホーンブレイク"
slug = "horn-breaker-hp"
characterId = 16
type = "commandNormal"
blockType = "high"
input = "4hp"

# Great Spin
[[moves]]
name = "Great Spin"
name_ja = "グレートスピン"
slug = "great-spin"
characterId = 16
type = "commandNormal"
blockType = "high"
input = "2hp"

# Double Arrow
[[moves]]
name = "Double Arrow"
name_ja = "ダブルアロー"
slug = "double-arrow"
characterId = 16
type = "targetCombo"
blockType = "high"
input = "j>5mp>5mp"

# Desert Storm
[[moves]]
name = "Desert Storm"
name_ja = "デザートストーム"
slug = "desert-storm"
characterId = 16
type = "targetCombo"
blockType = "high"
input = "6hp>5hp>5hp"

# Canyon Throw
[[moves]]
name = "Canyon Throw"
name_ja = "キャニオンスロー"
alternativeNames = ["Forward Throw"]
alternativeNames_ja = ["前投げ"]
slug = "canyon-throw"
characterId = 16
type = "throw"
input = "(lplk)"

# Falling Cliff
[[moves]]
name = "Falling Cliff"
name_ja = "フォーリングクリフ"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
slug = "falling-cliff"
characterId = 16
type = "throw"
input = "(4lplk)"
