# Standing Light Punch
[[move]]
name = "Standing Light Punch"
name_ja = "立ち弱パン"
alternativeNames = [ "Jab" ]
alternativeNames_ja = [ "小パン", "コパン" ]
slug = "luke-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5lp"
notes = [ ]
notes_ja = [ ]

# Standing Medium Punch
[[move]]
name = "Standing Medium Punch"
name_ja = "立ち中パン"
alternativeNames = [ "Strong" ]
alternativeNames_ja = [ "中パン" ]
slug = "luke-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5mp"

# Standing Heavy Punch
[[move]]
name = "Standing Heavy Punch"
name_ja = "立ち強パン"
alternativeNames = [ "Fierce" ]
alternativeNames_ja = [ "大パン" ]
slug = "luke-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "5hp"

# Standing Light Kick
[[move]]
name = "Standing Light Kick"
name_ja = "立ち弱キック"
alternativeNames = [ "Short" ]
alternativeNames_ja = [ "小足", "コアシ" ]
slug = "luke-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5lk"

# Standing Medium Kick
[[move]]
name = "Standing Medium Kick"
name_ja = "立ち中キック"
alternativeNames = [ "Forward" ]
alternativeNames_ja = [ "中足", "中アシ" ]
slug = "luke-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5mk"

# Standing Heavy Kick
[[move]]
name = "Standing Heavy Kick"
name_ja = "立ち強キック"
alternativeNames = [ "Roundhouse" ]
alternativeNames_ja = [ "大足", "大アシ" ]
slug = "luke-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "5hk"

# Crouching Light Punch
[[move]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱パン"
alternativeNames = [ "Crouching jab" ]
alternativeNames_ja = [ "しゃがみ小パン", "しゃがみコパン" ]
slug = "luke-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2lp"

# Crouching Medium Punch
[[move]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中パン"
alternativeNames = [ "Crouching jab" ]
alternativeNames_ja = [ "しゃがみ中パン" ]
slug = "luke-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2mp"

# Crouching Heavy Punch
[[move]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強パン"
alternativeNames = [ "Crouching strong" ]
alternativeNames_ja = [ "しゃがみ大パン" ]
slug = "luke-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "2hp"

# Crouching Light Kick
[[move]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱キック"
alternativeNames = [ "Crouching short" ]
alternativeNames_ja = [ "しゃがみ小足", "しゃがみコアシ" ]
slug = "luke-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2lk"

# Crouch Medium Kick
[[move]]
name = "Crouch Medium Kick"
name_ja = "しゃがみ中キック"
alternativeNames = [ "Crouching forward" ]
alternativeNames_ja = [ "しゃがみ中足", "しゃがみ中アシ" ]
slug = "luke-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2mk"

# Crouching Heavy Kick
[[move]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強キック"
alternativeNames = [ "Crouching forward" ]
alternativeNames_ja = [ "しゃがみ大足", "しゃがみ大アシ" ]
slug = "luke-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "low"
input = "2hk"

# Jumping Light Punch
[[move]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱パン"
alternativeNames = [ "Jumping jab" ]
alternativeNames_ja = [ "ジャンプ小パン", "ジャンプコパン" ]
slug = "luke-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jlp"

# Jumping Medium Punch
[[move]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中パン"
alternativeNames = [ "Jumping strong" ]
alternativeNames_ja = [ "ジャンプ中パン" ]
slug = "luke-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jmp"

# Jumping Heavy Punch
[[move]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強パン"
alternativeNames = [ "Jumping fierce" ]
alternativeNames_ja = [ "ジャンプ大パン" ]
slug = "luke-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jhp"

# Jumping Light Kick
[[move]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱キック"
alternativeNames = [ "Jumping short" ]
alternativeNames_ja = [ "ジャンプ小足", "ジャンプコアシ" ]
slug = "luke-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jlk"

# Jumping Medium Kick
[[move]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中キック"
alternativeNames = [ "Jumping forward" ]
alternativeNames_ja = [ "ジャンプ中足", "ジャンプ中アシ" ]
slug = "luke-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jmk"

# Jumping Heavy Kick
[[move]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強キック"
alternativeNames = [ "Jumping roundhouse" ]
alternativeNames_ja = [ "ジャンプ大足", "ジャンプ大アシ" ]
slug = "luke-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 1
type = "normal"
hitCount = 1
guardLevel = "high"
input = "jhk"

# Rawhide
[[move]]
name = "Rawhide"
name_ja = ""
slug = "rawhide"
characterId = 1
type = "commandNormal"
hitCount = 1
guardLevel = ""
input = "6mp"

# Suppressor
[[move]]
name = "Suppressor"
name_ja = ""
slug = "suppressor"
characterId = 1
type = "commandNormal"
hitCount = 1
guardLevel = "high"
input = "4hp"

# Outlaw Kick
[[move]]
name = "Outlaw Kick"
name_ja = ""
slug = "outlaw-kick"
characterId = 1
type = "commandNormal"
hitCount = 1
guardLevel = "high"
input = "4hk"

# Double Impact
[[move]]
name = "Double Impact"
name_ja = ""
slug = "double-impact"
characterId = 1
type = "commandNormal"
hitCount = 2
guardLevel = "high"
input = "6hp>hp"

# Triple Impact
[[move]]
name = "Triple Impact"
name_ja = ""
slug = "triple-impact"
characterId = 1
type = "commandNormal"
hitCount = 3
guardLevel = "high"
input = "lp>mp>hp"

# Nose Breaker
[[move]]
name = "Nose Breaker"
name_ja = ""
slug = "nose-breaker"
characterId = 1
type = "commandNormal"
hitCount = 1
guardLevel = "low"
input = "2mk>2hp"

# Snapback Combo
[[move]]
name = "Snapback Combo"
name_ja = ""
slug = "snapback-combo"
characterId = 1
type = "commandNormal"
hitCount = 4
guardLevel = "high"
input = "mp>mp>mp>mp"

# Sand Blast (Light)
[[move]]
name = "Sand Blast (Light)"
name_ja = ""
slug = "sand-blast-light"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "236lp"

# Sand Blast (Medium)
[[move]]
name = "Sand Blast (Medium)"
name_ja = ""
slug = "sand-blast-medium"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "236mp"

# Sand Blast (Heavy)
[[move]]
name = "Sand Blast (Heavy)"
name_ja = ""
slug = "sand-blast-heavy"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "236hp"

# Sand Blast (OD)
[[move]]
name = "Sand Blast (OD)"
name_ja = ""
slug = "sand-blast-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "236pp"

# Fatal Shot
[[move]]
name = "Fatal Shot"
name_ja = ""
slug = "fatal-shot"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "236[pp]>[pp]"
parentSlug = "sand-blast-od"

# Flash Knuckle (Light)
[[move]]
name = "Flash Knuckle (Light)"
name_ja = ""
slug = "flash-knuckle-light"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214lp"
properties = [ "chargeable" ]

# Flash Knuckle (Medium)
[[move]]
name = "Flash Knuckle (Medium)"
name_ja = ""
slug = "flash-knuckle-medium"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214mp"
properties = [ "chargeable" ]

# Flash Knuckle (Heavy)
[[move]]
name = "Flash Knuckle (Heavy)"
name_ja = ""
slug = "flash-knuckle-heavy"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214hp"
properties = [ "chargeable" ]

# Flash Knuckle (OD)
[[move]]
name = "Flash Knuckle (OD)"
name_ja = ""
slug = "flash-knuckle-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214[pp]"

# DDT
[[move]]
name = "DDT"
name_ja = ""
slug = "luke-ddt"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214[pp]>[pp]"
parentSlug = "flash-knuckle-od"

# Aerial Flash Knuckle
[[move]]
name = "Aerial Flash Knuckle"
name_ja = ""
slug = "aerial-flash-knuckle"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "j214p"
properties = [ "chargeable" ]

# Aerial Flash Knuckle (Charged)
[[move]]
name = "Aerial Flash Knuckle (Charged)"
name_ja = ""
slug = "aerial-flash-knuckle-charged"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "j214(p)"
parentSlug = "aerial-flash-knuckle"

# Aerial Flash Knuckle (OD)
[[move]]
name = "Aerial Flash Knuckle (OD)"
name_ja = ""
slug = "aerial-flash-knuckle-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "j214[pp]"

# Avenger
[[move]]
name = "Avenger"
name_ja = ""
slug = "avenger"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214k"

# Avenger (OD)
[[move]]
name = "Avenger (OD)"
name_ja = ""
slug = "avenger-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214[kk]"

# No Chaser
[[move]]
name = "No Chaser"
name_ja = ""
slug = "no-chaser"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214k>p"
parentSlug = "avenger"

# No Chaser (OD)
[[move]]
name = "No Chaser (OD)"
name_ja = ""
slug = "no-chaser-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "214[kk]>p"
parentSlug = "avenger-od"

# Impaler
[[move]]
name = "Impaler"
name_ja = ""
slug = "impaler"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "low"
input = "214k>k"
parentSlug = "avenger"

# Impaler (OD)
[[move]]
name = "Impaler (OD)"
name_ja = ""
slug = "impaler-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "guard"
input = "214[kk]>k"
parentSlug = "avenger-od"

# Rising Uppercut (Light)
[[move]]
name = "Rising Uppercut (Light)"
name_ja = ""
slug = "rising-uppercut-light"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "623lp"

# Rising Uppercut (Medium)
[[move]]
name = "Rising Uppercut (Medium)"
name_ja = ""
slug = "rising-uppercut-medium"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "623mp"

# Rising Uppercut (Heavy)
[[move]]
name = "Rising Uppercut (Heavy)"
name_ja = ""
slug = "rising-uppercut-heavy"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "623hp"

# Rising Uppercut (OD)
[[move]]
name = "Rising Uppercut (OD)"
name_ja = ""
slug = "rising-uppercut-od"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "623[pp]"

# Slam Dunk
[[move]]
name = "Slam Dunk"
name_ja = ""
slug = "slam-dunk"
characterId = 1
type = "special"
hitCount = 1
guardLevel = "high"
input = "623[pp]>[pp]"
parentSlug = "rising-uppercut-od"

# Vulcan Blast
[[move]]
name = "Vulcan Blast"
name_ja = ""
slug = "vulcan-blast"
characterId = 1
type = "super1"
hitCount = 1
guardLevel = "high"
input = "236pp"

# Eraser
[[move]]
name = "Eraser"
name_ja = ""
slug = "eraser"
characterId = 1
type = "super2"
hitCount = 1
guardLevel = "high"
input = "214pp"

# Pale Rider
[[move]]
name = "Pale Rider"
name_ja = ""
slug = "pale-rider"
characterId = 1
type = "super3"
hitCount = 1
guardLevel = "high"
input = "236kk"

# Sweeper
[[move]]
name = "Sweeper"
name_ja = ""
slug = "sweeper"
alternativeNames = [ "Forward Throw" ]
alternativeNames_ja = [ "前投げ" ]
characterId = 1
type = "throw"
hitCount = 1
input = "[5lplk]"

# Scrapper
[[move]]
name = "Scrapper"
name_ja = ""
slug = "scrapper"
alternativeNames = [ "Back Throw" ]
alternativeNames_ja = [ "後ろ投げ" ]
characterId = 1
type = "throw"
hitCount = 1
input = "[4lplk]"
