# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱P"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "manon-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 4
active = [4, 6]
recovery = 10
cancel = "C"
damage = 300
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 4
block = -1

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中P"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "manon-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

startup = 7
active = [7, 10]
recovery = 14
cancel = "C"
damage = 600
superArt = 500

[moves.frameAdvantage]
hit = 2
block = -1

[moves.driveGauge]
onHit = 1500
onBlock = -3000
onPunishCounter = -4000

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強P"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "manon-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"
notes = ["Forces a juggle state when hitting a mid-air opponent"]
notes_ja = ["空中ヒット時吹き飛びダウン"]

startup = 10
active = [10, 13]
recovery = 20
cancel = "SA"
damage = 800
superArt = 1000

[moves.frameAdvantage]
hit = 0
block = -3

[moves.driveGauge]
onHit = 3000
onBlock = -6000
onPunishCounter = -10000

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱K"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "manon-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

startup = 5
active = [5, 6]
recovery = 12
cancel = "C"
damage = 300
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 2
block = -2

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中K"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "manon-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

startup = 10
active = [10, 12]
recovery = 18
cancel = "C"
damage = 600
superArt = 700

[moves.frameAdvantage]
hit = -2
block = -5

[moves.driveGauge]
onHit = 1500
onBlock = -3000
onPunishCounter = -4000

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強K"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "manon-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"
notes = ["* Adds +17 frames of advantage on a standing opponent during a Punish Counter", "Forces a juggle state when hitting a mid-air opponent for a Punish Counter"]
notes_ja = ["※地上パニッシュカウンター時+17F", "空中パニッシュカウンター時吹き飛びダウン"]

startup = 15
active = [15, 17]
recovery = 26
damage = 900
superArt = 1000

[moves.frameAdvantage]
hit = -2
block = -6

[moves.driveGauge]
onHit = 3000
onBlock = -6000
onPunishCounter = -10000

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "manon-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 4
active = [4, 5]
recovery = 11
cancel = "C"
damage = 300
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = 2
block = -2

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中P"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ中P"]
slug = "manon-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"
notes = ["2 frames of recovery added when the attack misses"]
notes_ja = ["空振り時硬直2F増加"]

startup = 7
active = [7, 9]
recovery = 11
cancel = "C"
damage = 600
superArt = 500

[moves.frameAdvantage]
hit = 6
block = -1

[moves.driveGauge]
onHit = 1500
onBlock = -3000
onPunishCounter = -4000

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強P"
alternativeNames = ["Crouching fierce"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "manon-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

startup = 10
active = [10, 14]
recovery = 21
damage = 600
superArt = 1000

[moves.frameAdvantage]
hit = -2
block = -8

[moves.driveGauge]
onHit = 3000
onBlock = -6000
onPunishCounter = -10000

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱K"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "manon-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"
notes = ["Can be rapid canceled"]
notes_ja = ["連打キャンセル対応"]

startup = 5
active = [5, 6]
recovery = 13
damage = 200
scaling = ["Starter scaling 10%"]
scaling_ja = ["始動補正10%"]
superArt = 300

[moves.frameAdvantage]
hit = -1
block = -5

[moves.driveGauge]
onHit = 250
onBlock = -500
onPunishCounter = -2000

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "manon-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

startup = 8
active = [8, 11]
recovery = 16
damage = 600
superArt = 600

[moves.frameAdvantage]
hit = 2
block = -2

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -6000

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強K"
alternativeNames = ["Crouching roundhouse"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "manon-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"
properties = ["knockdown"]
notes = ["Knockdown time extended when attack lands as a counter or Punish Counter"]
notes_ja = ["カウンター/パニッシュカウンター時ダウン時間延長"]

startup = 11
active = [11, 12]
recovery = 27
damage = 900
superArt = 1000

[moves.frameAdvantage]
block = -12

[moves.driveGauge]
onHit = 3000
onBlock = -4000
onPunishCounter = -10000

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱P"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "manon-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"

startup = 5
active = [5, 14]
postLandingRecovery = 3
damage = 300
superArt = 300

[moves.driveGauge]
onHit = 500
onBlock = -1500
onPunishCounter = -2000

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中P"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン", "ジャンプチュウパン"]
slug = "manon-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"
notes = ["Forces a juggle state when hitting a mid-air opponent"]
notes_ja = ["空中ヒット時吹き飛びダウン"]

startup = 8
active = [8, 11]
postLandingRecovery = 3
damage = 700
superArt = 500

[moves.driveGauge]
onHit = 1000
onBlock = -2500
onPunishCounter = -4000

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強P"
alternativeNames = ["Jumping fierce"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "manon-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 12
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hp"
notes = ["Forces a slam knockdown when hitting a mid-air opponent"]
notes_ja = ["空中ヒット時叩きつけダウン"]

startup = 9
active = [9, 12]
postLandingRecovery = 3
damage = 800
superArt = 1000

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -5000

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱K"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "manon-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>lk"
notes = ["Has cross-up attack properties"]
notes_ja = ["めくり性能"]

startup = 6
active = [6, 14]
postLandingRecovery = 3
damage = 300
superArt = 300

[moves.driveGauge]
onHit = 500
onBlock = -1500
onPunishCounter = -2000

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中K"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "manon-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>mk"
notes = ["Has cross-up attack properties"]
notes_ja = ["めくり性能"]

startup = 7
active = [7, 12]
postLandingRecovery = 3
damage = 500
superArt = 500

[moves.driveGauge]
onHit = 1000
onBlock = -2500
onPunishCounter = -4000

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強K"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "manon-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 12
type = "normal"
hitCount = 1
blockType = "mid"
input = "j>hk"

startup = 11
active = [11, 15]
postLandingRecovery = 3
damage = 800
superArt = 1000

[moves.driveGauge]
onHit = 2000
onBlock = -4000
onPunishCounter = -5000

# Révérence
[[moves]]
name = "Révérence"
name_ja = "レベランス"
slug = "reverence"
characterId = 12
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "4hp"

# Tomoe Derrière
[[moves]]
name = "Tomoe Derrière"
name_ja = "トモエ・デリエール"
slug = "tomoe-derriere"
characterId = 12
type = "commandNormal"
hitCount = 1
blockType = "high"
input = "3hk"

# À Terre
[[moves]]
name = "À Terre"
name_ja = "ア・テール"
slug = "a-terre"
characterId = 12
type = "targetCombo"
hitCount = 2
blockType = "high"
input = "6mp>6mk"

# En Haut
[[moves]]
name = "En Haut"
name_ja = "アン・オー"
slug = "en-haut"
characterId = 12
type = "targetCombo"
hitCount = 2
blockType = "high"
input = "4mk>5mk"

# Temps Lié
[[moves]]
name = "Temps Lié"
name_ja = "タン・リエ"
slug = "temps-lie"
characterId = 12
type = "targetCombo"
hitCount = 2
blockType = "high"
input = "5hp>5hp"

# Allongé
[[moves]]
name = "Allongé"
name_ja = "アロンジェ"
slug = "allonge"
characterId = 12
type = "targetCombo"
hitCount = 2
blockType = "high"
input = "2hp>5hp"

# Manège Doré (Light)
[[moves]]
name = "Manège Doré (Light)"
name_ja = "マネージュ・ドレ（弱）"
slug = "manege-dore-light"
characterId = 12
type = "commandThrow"
input = "63214lp"

# Manège Doré (Medium)
[[moves]]
name = "Manège Doré (Medium)"
name_ja = "マネージュ・ドレ（中）"
slug = "manege-dore-medium"
characterId = 12
type = "commandThrow"
input = "63214mp"

# Manège Doré (Heavy)
[[moves]]
name = "Manège Doré (Heavy)"
name_ja = "マネージュ・ドレ（強）"
slug = "manege-dore-heavy"
characterId = 12
type = "commandThrow"
input = "63214hp"

# Manège Doré (OD)
[[moves]]
name = "Manège Doré (OD)"
name_ja = "マネージュ・ドレ（OD）"
slug = "manege-dore-od"
characterId = 12
type = "commandThrow"
input = "63214(pp)"

# Rond-point (Light)
[[moves]]
name = "Rond-point (Light)"
name_ja = "ロン・ポワン（弱）"
slug = "rond-point-light"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "236lp"

# Rond-point (Medium)
[[moves]]
name = "Rond-point (Medium)"
name_ja = "ロン・ポワン（中）"
slug = "rond-point-medium"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "236mp"

# Rond-point (Heavy)
[[moves]]
name = "Rond-point (Heavy)"
name_ja = "ロン・ポワン（強）"
slug = "rond-point-heavy"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "236hp"

# Rond-point (OD)
[[moves]]
name = "Rond-point (OD)"
name_ja = "ロン・ポワン（OD）"
slug = "rond-point-od"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "236(pp)"

# Dégagé (Light)
[[moves]]
name = "Dégagé (Light)"
name_ja = "デガジェ（弱）"
slug = "degage-light"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "214lp"

# Dégagé (Medium)
[[moves]]
name = "Dégagé (Medium)"
name_ja = "デガジェ（中）"
slug = "degage-medium"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "214mp"

# Dégagé (Heavy)
[[moves]]
name = "Dégagé (Heavy)"
name_ja = "デガジェ（強）"
slug = "degage-heavy"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "214hp"

# Dégagé (OD)
[[moves]]
name = "Dégagé (OD)"
name_ja = "デガジェ（OD）"
slug = "degage-od"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "214(pp)"

# Renversé (Light)
[[moves]]
name = "Renversé (Light)"
name_ja = "ランヴェルセ（弱）"
slug = "renverse-light"
characterId = 12
hitCount = 1
blockType = "high"
type = "commandThrow"
input = "623lp"

# Renversé (Medium)
[[moves]]
name = "Renversé (Medium)"
name_ja = "ランヴェルセ（中）"
slug = "renverse-medium"
characterId = 12
hitCount = 1
blockType = "high"
type = "commandThrow"
input = "623mp"

# Renversé (Heavy)
[[moves]]
name = "Renversé (Heavy)"
name_ja = "ランヴェルセ（強）"
slug = "renverse-heavy"
characterId = 12
hitCount = 1
blockType = "high"
type = "commandThrow"
input = "623hp"

# Renversé (OD)
[[moves]]
name = "Renversé (OD)"
name_ja = "ランヴェルセ（OD）"
slug = "renverse-od"
characterId = 12
hitCount = 1
blockType = "high"
type = "commandThrow"
input = "623(pp)"

# Renversé (Feint)
[[moves]]
name = "Renversé (Feint)"
name_ja = "ランヴェルセ（フェイント）"
slug = "renverse-feint"
characterId = 12
type = "action"
input = "623*p"

# Grand Fouetté
[[moves]]
name = "Grand Fouetté"
name_ja = "グラン・フェッテ"
slug = "grand-fouette"
characterId = 12
hitCount = 1
blockType = "high"
type = "special"
input = "*k"
parentSlugs = ["renverse-feint"]

# Arabesque
[[moves]]
name = "Arabesque"
name_ja = "アラベスク"
slug = "arabesque"
characterId = 12
hitCount = 1
blockType = "high"
type = "super1"
input = "236236*k"

# Étoile
[[moves]]
name = "Étoile"
name_ja = "エトワール"
slug = "etoile"
characterId = 12
hitCount = 1
blockType = "high"
type = "super2"
input = "214214*k"

# Pas de Deux
[[moves]]
name = "Pas de Deux"
name_ja = "パ・ド・ドゥ"
slug = "pas-de-deux"
characterId = 12
hitCount = 1
blockType = "high"
type = "super3"
input = "236236*p"

# Pas de Deux (Critical Art)
[[moves]]
name = "Pas de Deux (Critical Art)"
name_ja = "パ・ド・ドゥ (CA)"
slug = "pas-de-deux-ca"
characterId = 12
hitCount = 1
blockType = "high"
type = "super3"
input = "236236*p"

# Ouchigari
[[moves]]
name = "Ouchigari"
name_ja = "オーウチガリ"
alternativeNames = ["Forward Throw"]
alternativeNames_ja = ["前投げ"]
slug = "ouchigari"
characterId = 12
type = "throw"
input = "(lplk)"

# Uchimata
[[moves]]
name = "Uchimata"
name_ja = "ウチマタ"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
slug = "uchimata"
characterId = 12
type = "throw"
input = "(4lplk)"
