# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱パン"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "marisa-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中パン"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "marisa-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強パン"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "marisa-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"
properties = ["chargeable"]

# Marisa Style (Standing Punch)
[[moves]]
name = "Marisa Style (Punch)"
name_ja = "マリーザスタイル (立ちパンチ)"
slug = "marisa-style-stand-punch"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "5(hp)"
parentSlug = "marisa-stand-heavy-punch"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱キック"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "marisa-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中キック"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "marisa-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強キック"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "marisa-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Marisa Style (Standing Kick)
[[moves]]
name = "Marisa Style (Standing Kick)"
name_ja = "マリーザスタイル (立ち足)"
slug = "marisa-style-stand-kick"
characterId = 13
blockType = "low"
type = "commandNormal"
input = "5(hk)"
parentSlug = "marisa-stand-heavy-kick"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "marisa-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中パン"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ中パン"]
slug = "marisa-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強パン"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "marisa-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"
properties = ["chargeable"]

# Marisa Style (Crouching Punch)
[[moves]]
name = "Marisa Style (Crouching Punch)"
name_ja = "マリーザスタイル (しゃがみパンチ)"
slug = "marisa-style-crouch-punch"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "2(hp)"
parentSlug = "marisa-crouch-heavy-punch"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱キック"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "marisa-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "marisa-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強キック"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "marisa-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"
properties = ["chargeable"]

# Marisa Style (Crouching Kick)
[[moves]]
name = "Marisa Style (Crouching Kick)"
name_ja = "マリーザスタイル (しゃがみキック)"
slug = "marisa-style-crouch-kick"
characterId = 13
blockType = "low"
type = "commandNormal"
input = "2(hk)"
parentSlug = "marisa-crouch-heavy-kick"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱パン"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "marisa-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jlp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中パン"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中パン"]
slug = "marisa-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jmp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強パン"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "marisa-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jhp"
properties = ["chargeable"]

# Marisa Style (Jumping Punch)
[[moves]]
name = "Marisa Style (Jumping Punch)"
name_ja = "マリーザスタイル (ジャンプパンチ)"
slug = "marisa-style-jump-punch"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "j(hp)"
parentSlug = "marisa-jump-heavy-punch"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱キック"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "marisa-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jlk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中キック"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "marisa-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jmk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強キック"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "marisa-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 13
type = "normal"
hitCount = 1
blockType = "high"
input = "jhk"
properties = ["chargeable"]

# Marisa Style (Jumping Kick)
[[moves]]
name = "Marisa Style (Jumping Kick)"
name_ja = "マリーザスタイル (ジャンプキック)"
slug = "marisa-style-jump-kick"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "j(hk)"
parentSlug = "marisa-jump-heavy-kick"

# Light Two Hitter
[[moves]]
name = "Light Two Hitter"
name_ja = "ライトワンツー"
slug = "light-two-hitter"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "lp>lp"

# Medium Two Hitter
[[moves]]
name = "Medium Two Hitter"
name_ja = "ミドルワンツー"
slug = "medium-two-hitter"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "mp>mp"

# Heavy Two Hitter
[[moves]]
name = "Heavy Two Hitter"
name_ja = "ヘビィーワンツー"
slug = "heavy-two-hitter"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "hp>hp"

# Volare Combo
[[moves]]
name = "Volare Combo"
name_ja = "ヴォラーレコンボ"
slug = "volare-combo"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "jmp>mp"

# Caelum Arc
[[moves]]
name = "Caelum Arc"
name_ja = "カエルムアーク"
slug = "caelum-arc"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "j2hp"

# Magna Bunker
[[moves]]
name = "Magna Bunker"
name_ja = "マグナバンカー"
slug = "magna-bunker"
characterId = 13
blockType = "high"
type = "commandNormal"
input = "4hp"

# Novacula Swipe
[[moves]]
name = "Novacula Swipe"
name_ja = "ノバキュラスワイプ"
slug = "novacula-swipe"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "6mp>5hp"

# Novacula Thrust
[[moves]]
name = "Novacula Thrust"
name_ja = "ノバキュラシュート"
slug = "novacula-thrust"
characterId = 13
blockType = "high"
type = "targetCombo"
input = "6mp>5hk"

# Malleus Breaker
[[moves]]
name = "Malleus Breaker"
name_ja = "マレウスビート"
slug = "malleus-breaker"
characterId = 13
blockType = "overhead"
type = "targetCombo"
input = "3hp>3hp"

# Falx Crusher
[[moves]]
name = "Falx Crusher"
name_ja = "ファルクスクラッシュ"
slug = "falx-crusher"
characterId = 13
type = "targetCombo"
input = "6hk>6hk"

# Gladius (Light)
[[moves]]
name = "Gladius (Light)"
name_ja = "グラディウス（小）"
slug = "gladius-light"
characterId = 13
type = "special"
blockType = "high"
input = "236lp"
notes = ["Hold to change effect"]
notes_ja = ["ボタンホールドで性質変化"]

# Gladius (Medium)
[[moves]]
name = "Gladius (Medium)"
name_ja = "グラディウス（中）"
slug = "gladius-medium"
characterId = 13
type = "special"
blockType = "high"
input = "236mp"
notes = ["Hold to change effect"]
notes_ja = ["ボタンホールドで性質変化"]

# Gladius (Heavy)
[[moves]]
name = "Gladius (Heavy)"
name_ja = "グラディウス（大）"
slug = "gladius-heavy"
characterId = 13
type = "special"
blockType = "high"
input = "236hp"
notes = ["Hold to change effect"]
notes_ja = ["ボタンホールドで性質変化"]

# Gladius (OD)
[[moves]]
name = "Gladius (OD)"
name_ja = "グラディウス（OD）"
slug = "gladius-od"
characterId = 13
type = "special"
blockType = "high"
input = "236[pp]"
notes = ["Hold to change effect"]
notes_ja = ["ボタンホールドで性質変化"]

# Dimachaerus (Light)
[[moves]]
name = "Dimachaerus (Light)"
name_ja = "ディマカイルス（小）"
slug = "dimachaerus-light"
characterId = 13
type = "special"
blockType = "high"
input = "214lp>*p"

# Dimachaerus (Medium)
[[moves]]
name = "Dimachaerus (Medium)"
name_ja = "ディマカイルス（中）"
slug = "dimachaerus-medium"
characterId = 13
type = "special"
blockType = "high"
input = "214mp>*p"

# Dimachaerus (Heavy)
[[moves]]
name = "Dimachaerus (Heavy)"
name_ja = "ディマカイルス（大）"
slug = "dimachaerus-heavy"
characterId = 13
type = "special"
blockType = "high"
input = "214hp>*p"

# Dimachaerus (OD)
[[moves]]
name = "Dimachaerus (OD)"
name_ja = "ディマカイルス（OD）"
slug = "dimachaerus-od"
characterId = 13
type = "special"
blockType = "high"
input = "214[pp]>*p"

# Phalanx (Light)
[[moves]]
name = "Phalanx (Light)"
name_ja = "ファランクス（小）"
slug = "phalanx-light"
characterId = 13
type = "special"
blockType = "high"
input = "623lp"

# Phalanx (Medium)
[[moves]]
name = "Phalanx (Medium)"
name_ja = "ファランクス（中）"
slug = "phalanx-medium"
characterId = 13
type = "special"
blockType = "high"
input = "623mp"

# Phalanx (Heavy)
[[moves]]
name = "Phalanx (Heavy)"
name_ja = "ファランクス（大）"
slug = "phalanx-heavy"
characterId = 13
type = "special"
blockType = "high"
input = "623hp"

# Phalanx (OD)
[[moves]]
name = "Phalanx (OD)"
name_ja = "ファランクス（OD）"
slug = "phalanx-od"
characterId = 13
type = "special"
blockType = "high"
input = "623[pp]"

# Quadriga (Light)
[[moves]]
name = "Quadriga (Light)"
name_ja = "クアドリガ（小）"
slug = "quadriga-light"
characterId = 13
type = "special"
blockType = "high"
input = "236lk"

# Quadriga (Medium)
[[moves]]
name = "Quadriga (Medium)"
name_ja = "クアドリガ（中）"
slug = "quadriga-medium"
characterId = 13
type = "special"
blockType = "high"
input = "236mk"

# Quadriga (Heavy)
[[moves]]
name = "Quadriga (Heavy)"
name_ja = "クアドリガ（大）"
slug = "quadriga-heavy"
characterId = 13
type = "special"
blockType = "high"
input = "236hk"

# Quadriga (OD)
[[moves]]
name = "Quadriga (OD)"
name_ja = "クアドリガ（OD）"
slug = "quadriga-od"
characterId = 13
type = "special"
blockType = "high"
input = "236[kk]"

# Scutum
[[moves]]
name = "Scutum"
name_ja = "スクトゥム"
slug = "scutum"
characterId = 13
type = "special"
input = "214*k"

# Tonitrus
[[moves]]
name = "Tonitrus"
name_ja = "トニトルス"
slug = "tonitrus"
characterId = 13
blockType = "overhead"
type = "special"
input = "*p>*p"
parentSlug = "scutum"

# Procella
[[moves]]
name = "Procella"
name_ja = "プロケッラ"
slug = "procella"
blockType = "low"
characterId = 13
type = "special"
input = "*k"
parentSlug = "scutum"

# Enfold
[[moves]]
name = "Enfold"
name_ja = "エンフォルド"
slug = "enfold"
characterId = 13
blockType = "high"
type = "commandThrow"
input = "[lplk]"
parentSlug = "scutum"

# Javelin of Marisa
[[moves]]
name = "Javelin of Marisa"
name_ja = "マリーザジャベリン"
slug = "javelin-of-marisa"
characterId = 13
blockType = "high"
type = "super1"
input = "236236*p"

# Meteorite
[[moves]]
name = "Meteorite"
name_ja = "メテオリティス"
slug = "meteorite"
characterId = 13
blockType = "high"
type = "super2"
input = "214214*p"

# Goddess of the Hunt
[[moves]]
name = "Goddess of the Hunt"
name_ja = "アポロウーサ"
slug = "goddess-of-the-hunt"
characterId = 13
blockType = "high"
type = "super3"
input = "236236*k"

# Mounted Grace
[[moves]]
name = "Mounted Grace"
name_ja = "マウンテッドグレイス"
slug = "mounted-grace"
alternativeNames = ["Forward throw"]
alternativeNames_ja = ["前投げ"]
characterId = 13
type = "throw"
input = "[lplk]"

# Ponte Milvio
[[moves]]
name = "Ponte Milvio"
name_ja = "ミルヴィオブリッジ"
slug = "ponte-milvio"
alternativeNames = ["Back throw"]
alternativeNames_ja = ["後ろ投げ"]
characterId = 13
type = "throw"
input = "4[lplk]"
