# Standing Light Punch
[[moves]]
name = "Standing Light Punch"
name_ja = "立ち弱P"
alternativeNames = ["Jab"]
alternativeNames_ja = ["小パン", "コパン"]
slug = "zangief-stand-light-punch"
abbreviation = "S.LP"
abbeviation_ja = "立ち弱P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "5lp"
notes = []
notes_ja = []

# Standing Medium Punch
[[moves]]
name = "Standing Medium Punch"
name_ja = "立ち中P"
alternativeNames = ["Strong"]
alternativeNames_ja = ["中パン"]
slug = "zangief-stand-medium-punch"
abbreviation = "S.MP"
abbeviation_ja = "立ち中P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "5mp"

# Standing Heavy Punch
[[moves]]
name = "Standing Heavy Punch"
name_ja = "立ち強P"
alternativeNames = ["Fierce"]
alternativeNames_ja = ["大パン"]
slug = "zangief-stand-heavy-punch"
abbreviation = "S.HP"
abbeviation_ja = "立ち強P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "5hp"

# Standing Light Kick
[[moves]]
name = "Standing Light Kick"
name_ja = "立ち弱K"
alternativeNames = ["Short"]
alternativeNames_ja = ["小足", "コアシ"]
slug = "zangief-stand-light-kick"
abbreviation = "S.LK"
abbeviation_ja = "立ち弱K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "5lk"

# Standing Medium Kick
[[moves]]
name = "Standing Medium Kick"
name_ja = "立ち中K"
alternativeNames = ["Forward"]
alternativeNames_ja = ["中足", "中アシ"]
slug = "zangief-stand-medium-kick"
abbreviation = "S.MK"
abbeviation_ja = "立ち中K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "5mk"

# Standing Heavy Kick
[[moves]]
name = "Standing Heavy Kick"
name_ja = "立ち強K"
alternativeNames = ["Roundhouse"]
alternativeNames_ja = ["大足", "大アシ"]
slug = "zangief-stand-heavy-kick"
abbreviation = "S.HK"
abbeviation_ja = "立ち強K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "5hk"

# Crouching Light Punch
[[moves]]
name = "Crouching Light Punch"
name_ja = "しゃがみ弱P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ小パン", "しゃがみコパン"]
slug = "zangief-crouch-light-punch"
abbreviation = "C.LP"
abbeviation_ja = "屈弱P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "2lp"

# Crouching Medium Punch
[[moves]]
name = "Crouching Medium Punch"
name_ja = "しゃがみ中P"
alternativeNames = ["Crouching jab"]
alternativeNames_ja = ["しゃがみ中P"]
slug = "zangief-crouch-medium-punch"
abbreviation = "C.MP"
abbeviation_ja = "屈中P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "2mp"

# Crouching Heavy Punch
[[moves]]
name = "Crouching Heavy Punch"
name_ja = "しゃがみ強P"
alternativeNames = ["Crouching strong"]
alternativeNames_ja = ["しゃがみ大パン"]
slug = "zangief-crouch-heavy-punch"
abbreviation = "C.HP"
abbeviation_ja = "屈強P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "2hp"

# Crouching Light Kick
[[moves]]
name = "Crouching Light Kick"
name_ja = "しゃがみ弱K"
alternativeNames = ["Crouching short"]
alternativeNames_ja = ["しゃがみ小足", "しゃがみコアシ"]
slug = "zangief-crouch-light-kick"
abbreviation = "C.LK"
abbeviation_ja = "屈弱K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "2lk"

# Crouching Medium Kick
[[moves]]
name = "Crouching Medium Kick"
name_ja = "しゃがみ中K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ中足", "しゃがみ中アシ"]
slug = "zangief-crouch-medium-kick"
abbreviation = "C.MK"
abbeviation_ja = "屈中K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "2mk"

# Crouching Heavy Kick
[[moves]]
name = "Crouching Heavy Kick"
name_ja = "しゃがみ強K"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["しゃがみ大足", "しゃがみ大アシ"]
slug = "zangief-crouch-heavy-kick"
abbreviation = "C.HK"
abbeviation_ja = "屈強K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "low"
input = "2hk"

# Jumping Light Punch
[[moves]]
name = "Jumping Light Punch"
name_ja = "ジャンプ弱P"
alternativeNames = ["Crouching forward"]
alternativeNames_ja = ["ジャンプ小パン", "ジャンプコパン"]
slug = "zangief-jump-light-punch"
abbreviation = "J.LP"
abbeviation_ja = "ジャンプ弱P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lp"

# Jumping Medium Punch
[[moves]]
name = "Jumping Medium Punch"
name_ja = "ジャンプ中P"
alternativeNames = ["Jumping strong"]
alternativeNames_ja = ["ジャンプ中P"]
slug = "zangief-jump-medium-punch"
abbreviation = "J.MP"
abbeviation_ja = "ジャンプ中P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mp"

# Jumping Heavy Punch
[[moves]]
name = "Jumping Heavy Punch"
name_ja = "ジャンプ強P"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大パン"]
slug = "zangief-jump-heavy-punch"
abbreviation = "J.HP"
abbeviation_ja = "ジャンプ強P"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hp"

# Jumping Light Kick
[[moves]]
name = "Jumping Light Kick"
name_ja = "ジャンプ弱K"
alternativeNames = ["Jumping short"]
alternativeNames_ja = ["ジャンプ小足", "ジャンプコアシ"]
slug = "zangief-jump-light-kick"
abbreviation = "J.LK"
abbeviation_ja = "ジャンプ弱K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>lk"

# Jumping Medium Kick
[[moves]]
name = "Jumping Medium Kick"
name_ja = "ジャンプ中K"
alternativeNames = ["Jumping forward"]
alternativeNames_ja = ["ジャンプ中足", "ジャンプ中アシ"]
slug = "zangief-jump-medium-kick"
abbreviation = "J.MK"
abbeviation_ja = "ジャンプ中K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>mk"

# Jumping Heavy Kick
[[moves]]
name = "Jumping Heavy Kick"
name_ja = "ジャンプ強K"
alternativeNames = ["Jumping roundhouse"]
alternativeNames_ja = ["ジャンプ大足", "ジャンプ大アシ"]
slug = "zangief-jump-heavy-kick"
abbreviation = "J.HK"
abbeviation_ja = "ジャンプ強K"
characterId = 15
type = "normal"
hitCount = 1
blockType = "high"
input = "j>hk"

# Double Lariat
[[moves]]
name = "Double Lariat"
name_ja = "ダブルラリアット"
slug = "double-lariat"
characterId = 15
type = "special"
blockType = "high"
input = "(pp)"

# Double Lariat (OD)
[[moves]]
name = "Double Lariat (OD)"
name_ja = "ダブルラリアット (OD)"
slug = "double-lariat-od"
characterId = 15
type = "special"
blockType = "high"
input = "(ppp)"

# Screw Piledriver (Light)
[[moves]]
name = "Screw Piledriver (Light)"
name_ja = "スクリューパイルドライバー (弱)"
slug = "screw-piledriver-light"
characterId = 15
type = "special"
blockType = "high"
input = "{360}lp"

# Screw Piledriver (Medium)
[[moves]]
name = "Screw Piledriver (Medium)"
name_ja = "スクリューパイルドライバー (中)"
slug = "screw-piledriver-medium"
characterId = 15
type = "special"
blockType = "high"
input = "{360}mp"

# Screw Piledriver (Heavy)
[[moves]]
name = "Screw Piledriver (Heavy)"
name_ja = "スクリューパイルドライバー (強)"
slug = "screw-piledriver-heavy"
characterId = 15
type = "special"
blockType = "high"
input = "{360}hp"

# Screw Piledriver (OD)
[[moves]]
name = "Screw Piledriver (OD)"
name_ja = "スクリューパイルドライバー (OD)"
slug = "screw-piledriver-od"
characterId = 15
type = "special"
blockType = "high"
input = "{360}pp"

# Borscht Dynamite (Light)
[[moves]]
name = "Borscht Dynamite (Light)"
name_ja = "ボルシチダイナマイト (弱)"
slug = "borscht-dynamite-light"
characterId = 15
type = "special"
blockType = "high"
input = "j>{360}lp"

# Borscht Dynamite (Medium)
[[moves]]
name = "Borscht Dynamite (Medium)"
name_ja = "ボルシチダイナマイト (中)"
slug = "borscht-dynamite-medium"
characterId = 15
type = "special"
blockType = "high"
input = "j>{360}mp"

# Borscht Dynamite (Heavy)
[[moves]]
name = "Borscht Dynamite (Heavy)"
name_ja = "ボルシチダイナマイト (強)"
slug = "borscht-dynamite-heavy"
characterId = 15
type = "special"
blockType = "high"
input = "j>{360}hp"

# Borscht Dynamite (OD)
[[moves]] 
name = "Borscht Dynamite (OD)"
name_ja = "ボルシチダイナマイト (OD)"
slug = "borscht-dynamite-od"
characterId = 15
type = "special"
blockType = "high"
input = "j>{360}pp"

# Russian Suplex (Light)
[[moves]]
name = "Russian Suplex (Light)"
name_ja = "ロシアンスープレックス (弱)"
slug = "russian-suplex-light"
characterId = 15
type = "special"
blockType = "high"
input = "63214lk"
notes = ["When near opponent"]
notes_ja = ["近距離で"]

# Russian Suplex (Medium)
[[moves]]
name = "Russian Suplex (Medium)"
name_ja = "ロシアンスープレックス (中)"
slug = "russian-suplex-medium"
characterId = 15
type = "special"
blockType = "high"
input = "63214mk"
notes = ["When near opponent"]
notes_ja = ["近距離で"]

# Russian Suplex (Heavy)
[[moves]]
name = "Russian Suplex (Heavy)"
name_ja = "ロシアンスープレックス (強)"
slug = "russian-suplex-heavy"
characterId = 15
type = "special"
blockType = "high"
input = "63214hk"
notes = ["When near opponent"]
notes_ja = ["近距離で"]

# Russian Suplex (OD)
[[moves]]
name = "Russian Suplex (OD)"
name_ja = "ロシアンスープレックス (OD)"
slug = "russian-suplex-od"
characterId = 15
type = "special"
blockType = "high"
input = "63214(kk)"
notes = ["When near opponent"]
notes_ja = ["近距離で"]

# Siberian Express (Light)
[[moves]]
name = "Siberian Express (Light)"
name_ja = "シベリアンエクスプレス (弱)"
slug = "siberian-express-light"
characterId = 15
type = "special"
blockType = "high"
input = "63214lk"

# Siberian Express (Medium)
[[moves]]
name = "Siberian Express (Medium)"
name_ja = "シベリアンエクスプレス (中)"
slug = "siberian-express-medium"
characterId = 15
type = "special"
blockType = "high"
input = "63214mk"

# Siberian Express (Heavy)
[[moves]]
name = "Siberian Express (Heavy)"
name_ja = "シベリアンエクスプレス (強)"
slug = "siberian-express-heavy"
characterId = 15
type = "special"
blockType = "high"
input = "63214hk"

# Siberian Express (OD)
[[moves]]
name = "Siberian Express (OD)"
name_ja = "シベリアンエクスプレス (OD)"
slug = "siberian-express-od"
characterId = 15
type = "special"
blockType = "high"
input = "63214(kk)"

# Tundra Storm
[[moves]]
name = "Tundra Storm"
name_ja = "ツンドラストーム"
slug = "tundra-storm"
characterId = 15
type = "special"
blockType = "high"
input = "22hk"

# Aerial Russian Slam
[[moves]]
name = "Aerial Russian Slam"
name_ja = "エリアルロシアンスラム"
slug = "aerial-russian-slam"
characterId = 15
type = "super1"
blockType = "high"
input = "236236*k"

# Cyclone Lariat
[[moves]]
name = "Cyclone Lariat"
name_ja = "サイクロンラリアット"
slug = "cyclone-lariat"
characterId = 15
type = "super2"
blockType = "high"
input = "236236*p"

# Bolshoi Storm Buster
[[moves]]
name = "Bolshoi Storm Buster"
name_ja = "ボリショイストームバスター"
slug = "bolshoi-storm-buster"
characterId = 15
type = "super3"
blockType = "high"
input = "{720}*p"

# Bolshoi Storm Buster (Critical Art)
[[moves]]
name = "Bolshoi Storm Buster (Critical Art)"
name_ja = "ボリショイストームバスター (CA)"
slug = "bolshoi-storm-buster-ca"
characterId = 15
type = "super3"
blockType = "high"
input = "{720}*p"

# Hellstab
[[moves]]
name = "Hellstab"
name_ja = "ヘルスタブ"
slug = "hellstab"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "3mp"

# Knee Hammer
[[moves]]
name = "Knee Hammer"
name_ja = "ニーハンマー"
slug = "knee-hammer"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "6mk"

# Headbutt
[[moves]]
name = "Headbutt"
name_ja = "ヘッドバット"
slug = "headbutt"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "6hp"

# Cyclone Wheel Kick
[[moves]]
name = "Cyclone Wheel Kick"
name_ja = "サイクロンウィールキック"
slug = "cyclone-wheel-kick"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "6hk"

# Smetana Dropkick
[[moves]]
name = "Smetana Dropkick"
name_ja = "スメタナドロップキック"
slug = "smetana-dropkick"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "3hk"

# Flying Body Press
[[moves]]
name = "Flying Body Press"
name_ja = "フライングボディプレス"
slug = "flying-body-press"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "2hp"

# Flying Headbutt
[[moves]]
name = "Flying Headbutt"
name_ja = "フライングヘッドバット"
slug = "flying-headbutt"
characterId = 15
type = "commandNormal"
blockType = "high"
input = "j>8hp"
notes = ["During neutral jump"]

# Machine Gun Chops
[[moves]]
name = "Machine Gun Chops"
name_ja = "マシンガンチョップ"
slug = "machine-gun-chops"
characterId = 15
type = "targetCombo"
blockType = "high"
input = "5mp>5mp>5mp"

# Stomping
[[moves]]
name = "Stomping"
name_ja = "ストンピング"
slug = "stomping"
characterId = 15
type = "targetCombo"
blockType = "high"
input = "22mk>5mk>5mk"

# Body Slam
[[moves]]
name = "Body Slam"
name_ja = "ボディスラム"
alternativeNames = ["Front Throw"]
alternativeNames_ja = ["前投げ"]
slug = "body-slam"
characterId = 15
type = "throw"
input = "(lplk)"

# Capture
[[moves]]
name = "Capture"
name_ja = "キャプチュード"
alternativeNames = ["Back Throw"]
alternativeNames_ja = ["後ろ投げ"]
slug = "capture"
characterId = 15
type = "throw"
input = "(4lplk)"

# German Suplex
[[moves]]
name = "German Suplex"
name_ja = "ジャーマンスープレックス"
slug = "german-suplex"
characterId = 15
type = "throw"
input = "(6lplk)"

# Spinebuster
[[moves]]
name = "Spinebuster"
name_ja = "スパインバスター"
slug = "spinebuster"
characterId = 15
type = "throw"
input = "(3lplk)"

# Russian Drop
[[moves]]
name = "Russian Drop"
name_ja = "ロシアンドロップ"
slug = "russian-drop"
characterId = 15
type = "throw"
input = "(1lplk)"

# Brainbuster
[[moves]]
name = "Brainbuster"
name_ja = "ブレーンバスター"
slug = "brainbuster"
characterId = 15
type = "throw"
input = "(2lplk)"
